# -*- coding: utf-8 -*-
'''
Torrent-tv.ru Playlist Downloader Plugin configuration file
'''

__author__ = 'Dorik1972'

# Proxy settings.
# For example you can install tor browser and add in torrc SOCKSPort 9050
# proxies = {'http' : 'socks5h://127.0.0.1:9050','https' : 'socks5h://127.0.0.1:9050'}
# If your http-proxy need authentification - proxies = {'https' : 'https://user:password@ip:port'}
useproxy = False
proxies = {'http' : 'socks5h://127.0.0.1:9050',
           'https' : 'socks5h://127.0.0.1:9050'}

# Insert your Torrent-tv.ru playlist URL here
url=''

# TV Guide URL
tvgurl = 'http://1ttvapi.top/ttv.xmltv.xml.gz'

# Shift the TV Guide time to the specified number of hours
tvgshift = 0

# Download playlist every N minutes to prevent
# torrent-tv tracker forgetting us.
#
# 0 = disabled
updateevery = 0

# Channel logos mapping
logobase = 'http://1ttv.org/uploads/'
logomap = {
    u'0x0 Fireplace HD': logobase + 'H1VboxDJC7sE7x3nKXoYT0X5r4LIqD.png',
    u'0x0 Music HD': logobase + 'hFj4tnC5uqAgpod3doHnJGZxgZXaiP.png',
    u'1  Республиканский': logobase + 'QxsosYDL5JABz26VGnrz7PvDvbbHnE.png',
    u'1 HD': logobase + 'FtLnmUwjG18XJFEKYvLKjwUq1gwHVZ.png',
    u'1 MUSIC CHANNEL': logobase + '45atLSHAjViMISJinK8A0jQA34I0Fi.png',
    u'1 TV Georgia': logobase + 'V7mGlkUIBggg2MRuxohXaG2BzpqSTt.png',
    u'1+1': logobase + 'omm2Xc8xSVIT6Od6ca4QqMrEXw3jaK.png',
    u'1+1 International': logobase + '6fImIbJqJsF3pJQi2UuYRwtRyHMeaB.png',
    u'10(eser)': logobase + 'hwTC98CCLzKIViXXbjzxCe9hkP4aJ5.png',
    u'100% News': logobase + '9yEWvPmTcFS8lyQ5NjJ7vbYOa3bx1W.png',
    u'11 канал HD (Пенза)': logobase + 'j4S1ZmBG3rx6dL2gcX989SlB0SfRbz.png',
    u'112 Украина': logobase + '0AUjU7DOzZcpizC4UR19vDZqqthSe0.png',
    u'112 Украина HD': logobase + '0AUjU7DOzZcpizC4UR19vDZqqthSe0.png',
    u'12 Keshet Israel': logobase + 'ZiewqvPsv6cxNpP0OqcFjjLgSS7OHE.png',
    u'12 канал (Омск)': logobase + '5vukaqQtqpt7feoAWMlxFaRSi7NJfC.png',
    u'12 канал-ТНТ4 (Красноярск)': logobase + 'QRffpwjnXdgwDbroOK5cn7GVAAxC6t.png',
    u'1Music (Hungary)': logobase + 'Z1XhS3ANMsfXtROBMa7lMFITMPtMeb.png',
    u'1Music (Молдова)': logobase + 'Tj9idQugXvWdiecZd8kkQUJBPOGCsv.png',
    u'2+2': logobase + 'XHXBC3ghvhh100BNXylSgJLx5FVQgD.png',
    u'24 Horas (Испания)': logobase + 'cPYByklnBlkDRu1rBl1Nk8l7UqOIkZ.png',
    u'24 Украина': logobase + 'XfKEdfsy4S1zbE8n2tB1tNNe9IkrRP.png',
    u'24 Украина HD': logobase + 'o0kTfNaOXwzwgkvspP7fpQp2DCU2u9.png',
    u'26 регион (Ставрополь) HD': logobase + 'OHHLbUpvFvzkofjcBJOWTrYzZg7OWH.png',
    u'2x2': logobase + 'hTpJUV15GSTxZ5kJQGLcn42kCzKyEH.png',
    u'2x2 (+2)': logobase + 'ZPOhZle6vrDaulo2KMmyrCkkkLn7Ci.png',
    u'2x2 (+4)': logobase + 'p96aqLEhBQRCrTLMaycfbjOfOLqvNY.png',
    u'3+ (Latvia)': logobase + 'AHb8YFuSBRZbcILUWjCu6n6PtyH9Qh.png',
    u'31 канал (Казахстан)': logobase + 'q3wQypWHaIi8nP10TlqZ3SWRJujH2z.png',
    u'324 NOTICIES': logobase + 'xl4gKF3HjnAGl2JzQBljOvgmHTR04O.png',
    u'360 North': logobase + 'PqU8ChK1KhqWPKzRTdfUq42ZC3tK1L.png',
    u'360 градусов': logobase + 'K4tiqb5ajIgmxqh8X5moJuDjN7q5hx.png',
    u'360 градусов HD': logobase + 'K4tiqb5ajIgmxqh8X5moJuDjN7q5hx.png',
    u'360 Новости HD': logobase + 'cfdPKz2bawCEYFTMdGCNVvxyVsbTuW.png',
    u'360TuneBox': logobase + 'PsCgznk4UiWnKD1lNtp2GvdHS8XjVl.png',
    u'365 Дней': logobase + '0IZrVwoxtmjtgnWu5Dj4Hb8FRc8NIX.png',
    u'3ABN': logobase + 'AHMOuibR7xF0hyXCFVkvPyxOMCgqV4.png',
    u'3ABN Dare ot Dream': logobase + 'Hon12qyjLvLmluztdnBAeaBQG2VXh8.png',
    u'3ABN Francais': logobase + 'PowxwmlSw6YVRD488k4s6G03XQyrIn.png',
    u'3ABN International': logobase + 'tU6OAUj9oyAdV9TUvSXMsQthHHsdqN.png',
    u'3ABN Kidz (USA)': logobase + 'UaLZhDCUph0xIge5xE9pgcX48I77Mx.png',
    u'3ABN Proclaim! (USA)': logobase + 'aerGZMCcHEO5vOt3fgfU7l7fgKQ03N.png',
    u'3Sat': logobase + 'IqVTXKaeQc2Gio5cDxGZnsi97oeBO8.png',
    u'4 канал HD (Киев)': logobase + 'OAglc9f4b0OakOpmOZiXYXtvbzo6kZ.png',
    u'4 канал-Пятница (Екатеринбург)': logobase + 'auG4EjgiYjmJGXa3XAdvoOYIANgzUf.png',
    u'43 Канал HD (Туапсе)': logobase + '1mNoU1QXmcmK48eVTlnADtsEBmA2sN.png',
    u'47 канал': logobase + '8aHwrc5KVFI4FXwgPbBf5vjBSIQ52B.png',
    u'49 канал (Новосибирск)': logobase + 'COctPkIpDLR8rKNl9Bui7PUVyWZ5LH.png',
    u'4fun Dance': logobase + 'GeY3yZIGG5UoK2RAxtLBJhUuxoo9aQ.png',
    u'4Fun Gold Hits': logobase + 'DUs9iPeCTuonDyfML6yz9bJOwqmgl4.png',
    u'4Fun TV': logobase + 'MBRDVkacgvAn0zw4ceuI1ji9LxJFsb.png',
    u'5 канал (Украина)': logobase + '9La0uS6S8rMKr0BOh6vSCQLNiCqN7N.png',
    u'66 канал (Израиль)': logobase + 'ZNDGDdjbJMIB3owCIKosKGsUFe2En3.png',
    u'7 канал (Казахстан)': logobase + 'EHt5aLgecyICy4cJdur2nuaxKCl0vn.png',
    u'7 канал (Одесса)': logobase + 'xuDouCAz4Oo9UqRG28ctEruv1e9Osn.png',
    u'7 канал-Рен ТВ (Красноярск)': logobase + '3edpuWbBoRGAaIQOeQ5CZd0YxVKesn.png',
    u'7 ТВ': logobase + 'zSSkOQcBSJjAgA2WLQFzIkTlwqw5iD.png',
    u'78 канал': logobase + 'cj7bAfDJfk4TJHISxdqd0LYb3ZXqpD.png',
    u'78 канал HD': logobase + 'cLJLEUJDveYDll7FgICzi8i4lFjQol.png',
    u'7TV HD Murcia': logobase + 'vMcb2XvfS6XGWXM8Cm6lMYyeSfg84N.png',
    u'8 TV (Латино)': logobase + 'e7zlOfXYbwFYBNAgg1cphlrnQJRjEt.png',
    u'8 канал': logobase + 'wKPUJjcpZIfI5zBSZwNayOlv63zRNV.png',
    u'8 канал (Красноярск)': logobase + 'gh2BF8xc7CmqegvZOa4Y9TaermnvXA.png',
    u'8 канал (Новосибирск)': logobase + '481Ur07oxe8EBOE2pz5FY9cHGaX4ME.png',
    u'9 канал HD (Израиль)': logobase + 'gtzs7LmEAvKWM8wYH9aa7RZW5iprjR.png',
    u'A1 Смотри Один HD': logobase + '0NkmhF6gg1h8onQ856sUtEl8b5ikyZ.png',
    u'ABP Hindi vijesti': logobase + 'PheA88DwEpIzQ6Y4ZaVgd4PAyxtSzt.png',
    u'Abu Dhabi Drama': logobase + 'drs6R1ERL0bIKw6MdtgvY7mzhhiqee.png',
    u'Abu Dhabi TV HD': logobase + 'ejWH5qVf8XAWkc3HLQYTmEpYchtaIS.png',
    u'ACB TV': logobase + 'JgoFXmRqRHsE1MhQDqlrjSHnCzkO30.png',
    u'Accent TV': logobase + 'mE8pyqlR1eHlt3Fvlsmqk2MZCvneZG.png',
    u'Actualitatea TV': logobase + 'eo6ivMYMs4olDOv2kDu3likUtrB1lh.png',
    u'AD Sport 1 HD': logobase + 'ewjU0qgQQPtyIadk6ZmDM7kgBplyzh.png',
    u'AD Sport 2 HD': logobase + 'WnnTDAKno85TTnkmyIjCuCh2JWAAeg.png',
    u'Ajara TV HD (Georgia)': logobase + 'Ne80hvMcY4fqDupEEfMqL9f08lRgRp.png',
    u'Al Arabiya': logobase + 'RpfcTyls7BmUCCAJmOZrwgTLcDFMaG.png',
    u'AL Hadath HD': logobase + 'lMfvyFuSjl9U20xJmAsGvhA0xr3Y0v.png',
    u'Al Jazeera Documentary': logobase + 'IrA1ZKnwMrKVRbygiXDqpnL4ydw7t6.png',
    u'Al Jazeera English': logobase + '5ZfDU3kFx7mh5ntH0QZfagkjIWbZ4C.png',
    u'Al Kass Sports 1': logobase + 'ewEJ42j8JOCjt2Bw96LLmhNpfm4Z7s.png',
    u'Al Kass Sports 5': logobase + 'a2P26lHELlWIkLVb0xfAQ2yMLVoc9k.png',
    u'Al Rai': logobase + 'obGsASoNHiQQBMrrOAnxdT1lX5Rhb2.png',
    u'Alex Berlin TV': logobase + 'y4FrfRbEcIT6AoFKYjIdVAj6iMVJo4.png',
    u'AlKass Sports 2': logobase + '3FBVdvlkje7DSmiABjevLq0Og3L3dF.png',
    u'Almaty tv': logobase + '4u88pLLLIZTwBNOgpMC1DtlWQifWK4.png',
    u'Alpha Media': logobase + 'Dy3jAhESTbKt6YAOVxH99nnqOqsZXq.png',
    u'AMC': logobase + 'rozrC8ZPYA1YGajyow35doeVcaQzpa.png',
    u'Amedia 1': logobase + 'NbdxfVLZtRUQzzfvQPNRVMVAl2Hp0O.png',
    u'Amedia 2': logobase + 'KY8tm4Runi4FpgUYcAn5WoeXqiD3Y5.png',
    u'Amedia Hit': logobase + 'HdnTfcZCgP7Odm1cOKNq9j4yJDRiFP.png',
    u'Amedia Hit HD': logobase + 'HdnTfcZCgP7Odm1cOKNq9j4yJDRiFP.png',
    u'Amedia Premium': logobase + 'ornzQpk6WCW6xk0lyBhlwqH8u2QyU7.png',
    u'Amedia Premium HD': logobase + 'ornzQpk6WCW6xk0lyBhlwqH8u2QyU7.png',
    u'Amga tv': logobase + 'ggof9xh4JVm9vSyPMgSRrbbVmpzyK6.png',
    u'Ani': logobase + 'vui1cRrE05CZv1N9Qb20jJ6mTFOJue.png',
    u'Animal Planet': logobase + '45.png',
    u'Animal Planet HD': logobase + '9HZGan5rQItVQOfnB91FGqyJXjoqYV.png',
    u'Anixe': logobase + 'IY3mzyzRnOMN0URZvHOgpV1Fu1SQow.png',
    u'ANTENA 3 (Spain)': logobase + 'vuNPdYefENYEFbKMUmgaIYmZXkf1oN.png',
    u'Anyday 3D': logobase + 'Q9gPrtyM73PzW5Jlf0pXnjCJcT0Tq7.png',
    u'Anyday HD': logobase + 'nZ0Aa5bcpThFFTGvBUfW65GTgVoH6c.png',
    u'Arabica TV': logobase + 'cdEYtkiYIxYHxthy09hm3MIjZfw59C.png',
    u'ARD Das Erste': logobase + 'BNSftp1tgy2zCDXCdkqqP2iGaxkkYl.png',
    u'ARIANA TV Afganistan': logobase + '5WWmwVC2dY0HgJYNzCPiQOTik2FFtr.png',
    u'Arirang TV': logobase + '1pqJ1GzFAZ9AnEYWnd50vPruDXvBRZ.png',
    u'Armenia 1 Satellite HD': logobase + 'tTWfwTOCCAnkBOYuYrMOqtBXjGp9Va.png',
    u'Armenia TV Satellite': logobase + 'M4UAMT6cEyL3zuim9fzy38vZRkIfKq.png',
    u'Astana TV': logobase + 'mOkPycOGSRXh2jtsPxsrEsItPrsPiJ.png',
    u'Astrakhan.Ru live': logobase + 'AoYdzaHGvvNQv7cIslo8ABexpgRnAH.png',
    u'astro AWANI (Индонезия)': logobase + '7US005WT15rb8ajcfcE8avb3rhHVMe.png',
    u'ATR': logobase + 'uggqxQxxDTuz1P1mY4PZdlRcAKow3F.png',
    u'Atreseries TV (Spain)': logobase + 'qBuXHgroPkrGpNwKomZyp9T39u5c3c.png',
    u'ATV (Венгрия)': logobase + 'g2v1gLo1qLj9Zp8Gcuy2XqML3ieNvd.png',
    u'ATV Azerbaycan': logobase + 'yx7GzFSH3BlxYYa0Nuq4eiVRqxZSa5.png',
    u'Aurora TV': logobase + 'uMQrMUdm0ZLvmH2n72kXEQqf8Kysj4.png',
    u'Az TV': logobase + 'FB2qxgNm8xTU6YiR2fY1jH4PIRR2SF.png',
    u'Babestation': logobase + 'DbvHMminWOobAbD3IliRECsG8RH6uL.png',
    u'Baby TV': logobase + 'IV1Puqsxki1WGIxut4QLpRUZ7yPR8c.png',
    u'Baden TV': logobase + 'n6isIjMCHNS8wc5RlA1krB3mwsIu43.png',
    u'BB-MV Lokal-TV': logobase + '7zCVz9skVBkjpa6sQpjljwkn1DjfU8.png',
    u'BBC Arabic': logobase + 'LEXgStjx1ZSGakEm1mF5wmA6fflzsa.png',
    u'BBC Brit HD (Polska)': logobase + '0lhHepoLPDGQjfupU8sFxlSNTNk43b.png',
    u'BBC Earth HD (Polska)': logobase + 'cBtECu4MsPAYmq1EJnW4QhGEArTYML.png',
    u'BBC HD (Nordic)': logobase + '3s2pkltINbWctXlmqdgWGeFugYeDgY.png',
    u'BBC Iran': logobase + 'VA6KwESWRCYGLdLymwp1byO98kk6OH.png',
    u'BBC Lifestyle HD (Polska)': logobase + 'h8y5EyHDI63a5t6LfqrKaDeqWauE6M.png',
    u'BBC World News': logobase + '8cSYWwvq6BAzcGDjJODvCGQYGJ2c4S.png',
    u'Beblack Africa': logobase + 'cLxKsli1Vn2Bijsof5BdUjtMIbwAO0.png',
    u'Beblack Caribbean': logobase + 'bpIRXECpEkgl91dRUlTH1AqUXUzzrL.png',
    u'Beblack Classik': logobase + 'mNnRfrogufRdLz5VW27XyYOduvs06N.png',
    u'BEST Films HD': logobase + 'Vl495JI85Hq960KAlIFfkO7A2LMRRn.png',
    u'Betis TV': logobase + 'Lu7ytJukbXsdZO7ipjge3hHUxp9sFY.png',
    u'BFM Business (France)': logobase + 'QJW82U4H7NvAs2NbZuSt8Gp9TRWMjm.png',
    u'BFM Paris': logobase + 'rOyMbuE29Wlaw72MegBnurkZCNVrOF.png',
    u'BHTV (Latino)': logobase + 'trLraYHxRdIII59tVAG2fn0x3sNC0d.png',
    u'BiT Bulgaria': logobase + 'v09xoP3txCrbM5NlVLWn8ImlmSvAXL.png',
    u'Bloomberg': logobase + 'OTsoNZRT8xjXz5nnTICPCQRvNLjBal.png',
    u'Blue Hustler': logobase + 'wgAR4TI1xdd2LAtnbkpvFAfnnn5Uru.png',
    u'BNT1 BULGARIA': logobase + 'ObJNqi46rwfyvODnaTOyj739Gq9ecV.png',
    u'BNTV (Bosnia)': logobase + '4woz8tJq9ukCECCCy7kxdyjYpXaTLl.png',
    u'Bollywood HD': logobase + 'HXzWxtMxmXkrpgr88Kh8Z1A8F6o5dK.png',
    u'BOLT HD': logobase + 'EEZrUgR0IgyOp97DI8sGPT78J40Doq.png',
    u'Boomerаng TV': logobase + '1QcRQ8LAb0FMno8FcHMNh7alKiCuoO.png',
    u'Boutique TV': logobase + 'bDSWVUfAEYN9VS25roxW52xO1pj6qp.png',
    u'Boutique TV (Россия)': logobase + 'drRa7yCmfga29eURYi0Fd7FaYKicid.png',
    u'BPTV 1': logobase + 'EWfCQuhHoa3TYT5cODP5IYr4dh38GF.png',
    u'BPTV 2': logobase + 'DGIQ1LvLUOqPGtLNMFmkwXxyvfMJxh.png',
    u'BR HD': logobase + 'thBVAa5XzrXbNhqUU1mBsGZ7VkwEgT.png',
    u'Brain TV HD': logobase + '2tc8t3vKfw1wxJ3wRG7QIEaMeF3fI6.png',
    u'Brazzers TV': logobase + 'VPCmFsMfpnB0pg9VBzvUG5TkRcHTsR.png',
    u'Brazzers TV Europe': logobase + 'OmVBp3Kz4Lx722dq2e1OxE26QSxrDA.png',
    u'Bridge HD': logobase + 'P7JEo7cGv1dtk6X69SkfEQeiVrQvXj.png',
    u'Bridge TV': logobase + 'QA0CGVMTYbba5NbfO8TEJFSVBZsHvc.png',
    u'Bridge TV Classic': logobase + 'NCuKRKNU2rwc8DkpF555fINSz5xaIc.png',
    u'Bridge TV Dance': logobase + 'ofmgiZlRmwOZtTaYtUtfErZS3ODDDM.png',
    u'Bridge TV Русский хит': logobase + 'nTwadtVZmhLHyHK3AG3t2q9W6ohrgo.png',
    u'Bronxnet Channel': logobase + 'bMvDktqgNrax7OmZkbKVFh89ds2JY6.png',
    u'BTV HD (Moldova)': logobase + 'vrLSDaBnU5035aImpujug0DRKrxN2O.png',
    u'Buy Home TV HD': logobase + 'TKVaIssajFIiEe3LprNJgbxKgNibDR.png',
    u'C Music TV HD': logobase + 'YhtkJhsV8NKwm4FGWhQZDmYcW0TYQS.png',
    u'C-Span (USA)': logobase + 'kV5tJbkTg3geFZXeQrHdSuaUCunKgL.png',
    u'C-Span 2 (USA)': logobase + 'nGamhICamAIsFLwEx2UohLmhLMIehw.png',
    u'C-Span 3 (USA)': logobase + '5zGNqmWB4yyohwp95O35B9gWFrzsw6.png',
    u'California Music Channel': logobase + '6yPrhzuR4DgLpEnFbLPjLxnAJET22x.png',
    u'Canal 25 (Latino)': logobase + 'D1gomTD5MoUUiRZRYzfY5d0fHNP2js.png',
    u'Canal 3': logobase + 'mS0OlRJCzxJ613UwekN2rFrYJKfYNe.png',
    u'Canal Congreso': logobase + 'jsqdhxGGSlueYUbP7eenPc78mFyeyX.png',
    u'Canal Japanet DX': logobase + 'Eusi09Asg1v6ByVblkTJ9w0Xz443KM.png',
    u'Canal Once': logobase + 'ZsXAufR6Mpb1CiKg4Tkwwt2kukWVLE.png',
    u'Candy TV HD': logobase + 'ZQ6VNc4wzDy0c49j7D1GO6JUDLmcES.png',
    u'Cannali TV': logobase + 'mWihswziOSnlec57b6a7CQuMGACpKC.png',
    u'Capital TV': logobase + 'gWLL0ORsWW814FjcN1xYyrrDbXym6R.png',
    u'CARINA TV (Italia)': logobase + '4TnlkZRWuavkVhAj9GE6dYXRA23E6S.png',
    u'Cartoon Network': logobase + 'NTNQLLri3Hh9iqYjW7VEkFYJsTLjk9.png',
    u'CBC Sport HD': logobase + 'yp6LYxckUxFn7Yuru4UJQKPRUI4WZ2.png',
    u'CBC TV': logobase + 'YtEXBCyrrONkHOqxDPgsxWFXQLUh45.png',
    u'CBN (Espanol)': logobase + 'IpzqPkWA9irtxKrjkkEQyxivI72q4r.png',
    u'CBN (USA)': logobase + 'BIDTN3LGbaOxdB0q1oewsYxoalzFg2.png',
    u'CBS News HD': logobase + 'p83uuzAOgD2EpLuxpM4RudoFq7KY9v.png',
    u'CBS Reality': logobase + 'QbWaD2vNgLRLY0Hsccg3nf9azAXRld.png',
    u'CCTV 4': logobase + 'PsrMNDhKrEgCJA5lAR9UUtBlOI4uJg.png',
    u'CentoXCento TV': logobase + 'dPuPlqJtkLMRy7NmOhyHDfL0PJqYj4.png',
    u'CGTN': logobase + 'TyWVFvKwV3lOYYXWVJSj8HMu5AodJr.png',
    u'CGTN Documentary': logobase + 'dqoArqO8dd09vzsSSQPqLUj5wM9O9M.png',
    u'CGTN Documentary': logobase + 'TDlz18otonOznOvHSpvzApK2ME3P8b.png',
    u'CGTN Espanol': logobase + '3e2nToMxIs2lsNeLnKZgx39Lm6lxtr.png',
    u'CGTN Русский': logobase + 'DcaE92lKRSDFBPlYUnsNRauFLbotKu.png',
    u'Channel 20 (Israel)': logobase + 'FnN5QmA4N8sdyPYhQVekt5zy5DdWkU.png',
    u'Channel 21': logobase + 'SmIIAooatNUekMHrjgWF2WAcYPBJwx.png',
    u'Channel AKA': logobase + 'ICwvqjyvRu3IK4uwXC0e9j3CtGX33H.png',
    u'Channels 24': logobase + 'HwQLjkmeRfjnLPQsG17ljSAe6J7jnl.png',
    u'CHAUla.tv': logobase + '05lcBTkYb6x45t8btP4pU92pgvDijK.png',
    u'Cinema': logobase + 'wpspDreDq2gIcKq4flMLwItJsG7yyx.png',
    u'Cinema HD (Космос ТВ)': logobase + 'Wt3gwpG9FAPiO6qw0fts8yDTJjE2iV.png',
    u'City tv': logobase + 'dnh1EYajDagMWQB7684M48WovZKjUh.png',
    u'Clik TV HD': logobase + 'E7l6l7w9goponNvFoHMvUcEK4iufzu.png',
    u'Clubbing TV HD': logobase + 'CLYAjlwDYpQz2EuFox2FDJ0xtxwZHQ.png',
    u'CNBC': logobase + 'GoIM168L5VukllPhUODkjrtQmjr13i.png',
    u'CNC World': logobase + 'JcDLImpt4YyZ1URpt3ZeP8cUXxQRhE.png',
    u'CNN (Chile)': logobase + '25zaU8uUglUyykPsevr8qT6VviqIuO.png',
    u'CNN (Turkey)': logobase + 'ZBjWLCDCR2h9hzgWgsU0LTKFbpyOcy.png',
    u'CNN International': logobase + 'lIwbRbM3ve4ixhFXp75Oap9nzcO71G.png',
    u'Comedy Central Austria': logobase + '90vbtB2TQshhIcEU3N4RXfG0nxHkIr.png',
    u'Comedy TV (Georgia)': logobase + 'ebnMPVIsB8oT8tFLwFTxdcMTZV4ZDR.png',
    u'Country Music 4U': logobase + 'GWxiE3PLuHN6wqxaB9NB3gz09Dz3dr.png',
    u'Credo TV': logobase + '0BTblERJkRHNF5cHIp3KnLRMgBJB9u.png',
    u'Da Vinci Learning': logobase + 'Yl6p1IDDkZxxiUa3p2JxI66mIlOPns.png',
    u'DD Lok Sabha': logobase + 'X45SitdQco6MK7bUb6NdOy276VtDi7.png',
    u'DD Punjabi': logobase + '1QoojFgESa1mprnJD6zlyKYhIIzL7n.png',
    u'DeeJay TV': logobase + '8nCmCKKg77T73lSoCksvImtOsbpxsQ.png',
    u'Deluxe Music': logobase + 'eBgdUCx50YVmWhj6LlQPyBmPvVR19x.png',
    u'Deutsche Welle': logobase + 'RnqBDfde1HP4OkZhXWlKB1xkHi6Io9.png',
    u'Deutsches Musik Fernsehen': logobase + 'o5Em9yhi2NzjIwa8K61Rqi2hl7Dhi7.png',
    u'Discovery Channel': logobase + 'oKx1ImWVRT3AK3DHYWUVc71JZUkwu5.png',
    u'Discovery Channel HD': logobase + 'SmWnYlOvkJn8GzttT2UY0vmo8PYfMg.png',
    u'Discovery Historia Polska': logobase + 'DQvOBosiJ3hV7ThJ6LvLCpj54QJES1.png',
    u'Discovery Science': logobase + 'GAaO3EfDwMuHAIelG4gYW6TDEYbLnS.png',
    u'Discovery Scienсe HD': logobase + 'i8ALRNkouYmFxluW4UXn2ZKaOrGZ5o.png',
    u'Discovery Showcаse HD': logobase + 'bSyT90RisSnnrCJvZsRXTCTFWWdRf6.png',
    u'Disney Channel': logobase + 'JxEjTeXwExjnxutQGKJBmMI85tpNqK.png',
    u'Disney Channel (+2)': logobase + 'nn6LfV3ROFIiPztSN76lNa1OSkPFzp.png',
    u'Disney Channel (+4)': logobase + 'g7li3Aq4jQTTZn6FfLeylF76wYF4OS.png',
    u'Disney Channel Deutschland': logobase + 'e1kmDfajivvLrIILyvMIpAT9JeRd7e.png',
    u'Divinity TV (Spain)': logobase + 'q2S5vg5C0z4RE5O37rrVnqpQ3Svnm8.png',
    u'DMAX Austria': logobase + '2IJzdBpGH5lY60LJz95mreaKtrGCUu.png',
    u'DocuBox': logobase + '4ZjuKuTHFCuXqKkEmKYGcBFe6UK5z4.png',
    u'Dog TV': logobase + 'NblfllG2mrqX3Zrb36rv7hLUe2sG1R.png',
    u'Dorcel TV HD': logobase + 'nMh8B5gWWKxDz5wo5nUW7iVj9UlWgd.png',
    u'Dream': logobase + 'uXbdtjZ6XVzaQ51mRI4YGX2GnTkKig.png',
    u'Dream Turk': logobase + 'fkHWroHwYXfGhNhnByIWRzl5XaVDDa.png',
    u'DTX': logobase + 'bx7MosYUikfuwwIOzx2elT6Dh7h50I.png',
    u'Dubai One HD': logobase + 'QGqpskQOlMeTKGz3bDauTT7xdI8cvc.png',
    u'Dubai Sport TV': logobase + 'YOHsneUH8LFddkCFIGJeHFUavj1g1N.png',
    u'Dubai Sports 2': logobase + 'Tp3ShdXCq6WNU0UDvzxpw1yTMBm9to.png',
    u'Dubai TV HD': logobase + 'mQcQKZ5j3OLWvriHlaXfnsGuTD6imZ.png',
    u'Dubai Zaman': logobase + 'a47JBZ25ueEiEzsOInRhV3TcllufhF.png',
    u'Duga Plus': logobase + '3H1XfxV8aWOkC6UdZ4W31uRgKcRijd.png',
    u'Dunya TV': logobase + '2Iu1oHCcgpHzMOryMult4HYBxDoIwR.png',
    u'Dusk TV': logobase + '5j0MFmxPLBN36rJR2yYxgnOOHa23gh.png',
    u'DW TV (Индонезия)': logobase + 'LUjYxVgplIpplQNSaEFTQv5SGRwwjU.png',
    u'E! Entertainment TV': logobase + 'lebXFXnEIeEIpqbiE7Te743zlftPVG.png',
    u'Eger TV': logobase + '42osHDng9XI5T2yyFCM4CLV75wn1K2.png',
    u'Elbekanal Schonebeck': logobase + 'BV9TVbCFCtZZKC2dkxRLbNYgIq6cWA.png',
    u'Emarat HD': logobase + 'qkG5NTzWZioqaqwdXHniUvEPVC6rtD.png',
    u'English Club TV': logobase + 'Hf5RUQ91cEGtHoaK3GK6VIZlJ8Leql.png',
    u'Enter Film': logobase + '8FPA5SCEIj35fBO8yrULnefW4NzIzk.png',
    u'EO TV': logobase + 'HvSVkXfnHA9FOGTpkvw2eqtqd3E5nf.png',
    u'Epoque': logobase + 'eULbHv3DyublWF2rAhw38DV63cV3V9.png',
    u'EPOQUЕ HD': logobase + 'EKfkYWRSkYiN76MxCZCjawxewjBOYY.png',
    u'Erkir Media TV': logobase + 'srS8LqVDwobCyAC4NzrBh2bVDW9PCn.png',
    u'EROX HD': logobase + 'Hmke97pFjdznlPcNgXcUPGGUa2zO4g.png',
    u'Eska TV Extra': logobase + '4NZw34ITXBGy0jBfhfXhwp2LR0q1cL.png',
    u'ETV': logobase + 'EXXEf0i7yGRDFttKSwBq4CLoGiuxbW.png',
    u'ETV2': logobase + 'dR4fj3bOJ4PAqBEKskc9yLNj0unwAD.png',
    u'EU Music HD': logobase + 'yLnRLNzZDy96g3XPY9EaSM8wqCS3ma.png',
    u'Eureka HD': logobase + 'bLdrAOaL1qzqbDo8d2Z8lO6lyg7bO6.png',
    u'EuroNews': logobase + 'Vb3fP5gUK0q40WuzYeUhMT7RQmDg27.png',
    u'EuroNews France': logobase + 'heUTD1jVbIs8rZQu3wGtqF4ChfJ6E5.png',
    u'EuroNews German': logobase + '51R7dGVwaNiS2fEwww7VwPBJcLnnuT.png',
    u'EuroNews Greek': logobase + 'JItod7zsqX92UtfPQvUaywTxEJtOzR.png',
    u'EuroNews Italian': logobase + 'seIGMcCQFi2k2GXm0MaqfO7nuGysc4.png',
    u'Europa Plus TV': logobase + 'PkatgpdmA4ArsgSG5shu0ZCQQ5RgMx.png',
    u'Eurosport 1': logobase + 'QA9jgUaQRrE4vMno04eM3aUrklXOce.png',
    u'Eurosport 1 Deutschland': logobase + 'XyhXUTmdExruuJsmu4F6v3sjZ9z1IV.png',
    u'Eurosport 1 HD': logobase + 'DpFTzUEA3y67Z6ObTPF4xH0XLNRAZm.png',
    u'Eurosport 2': logobase + 'qYbdkVFDkhGqTAjXlRtIj2Fg45bmrm.png',
    u'Eurosport 2 HD': logobase + '0mo5WOW3xn7FmcIRM9PMZxb2Zgad86.png',
    u'EvilAngel': logobase + 'FufZ2heFswzvAbRkTQZs8UJBYGsxuG.png',
    u'Evine Live (USA)': logobase + 'CxLhLLAnI8HeqTR3tTHsGM0gQhycKv.png',
    u'EWTN - Katholisches Fernsehen': logobase + 'XM9LR6lzQ8F4yCLo6l0rf78q9056kC.png',
    u'EWTN UK and Ireland': logobase + 'maP6bdwOGv77xHPvRnKBHww9cmG2oV.png',
    u'EWTN Ukraine': logobase + 'Mt1hh5UO6J5f4UQOy4ETnyN08R1wK5.png',
    u'Extremadura TV': logobase + 'jzo6ZI8gyCrYIeb3WFGUy8sLn30TKF.png',
    u'Extreme Sports': logobase + '21FhIqWK82JDPNuLTEIC9hSO2EHfks.png',
    u'EТV+': logobase + '64BTq8C5ZglQeKE9Ckv8OvnxFrjyGH.png',
    u'Familia Domashniy': logobase + 'iRrgl4xiCvibdxWfiQcVUWuYCYCI9K.png',
    u'FAP TV 2': logobase + 'YVmUBY8cBPO8IoL4djlyeKCDbs6f0p.png',
    u'FAP TV 2 HD': logobase + 'KqVXT8GPTPuPEM87hZSqDwajqcBBgY.png',
    u'FAP TV 3': logobase + 'S5gXPPcF53lFHQ3kgJofKMQudRQKPt.png',
    u'FAP TV 4': logobase + 'xv1QyBV2OkaDbZ1ebRB2FWwfw40BR5.png',
    u'FAP TV Amateur': logobase + 'LGfemDTp3Z3mvhn1aKSGVvtlNu5zMF.png',
    u'FAP TV Anal': logobase + '1PVgf85c4DjIsiWEikpEHDV1j1m6ph.png',
    u'FAP TV BBW': logobase + 'PHnwbskpP4oixpMjlJKgGvTAajXFSg.png',
    u'FAP TV Compilation': logobase + 'FXT4PI3HHWIGlk49jRpHyGQBTTVbmt.png',
    u'FAP TV Gay': logobase + 'vJB3tfzXuDX8R7eLXV63tCFgxnOgP1.png',
    u'FAP TV Legal Porno': logobase + 'QMv8xcYgTaW9108ymib6XyWXRMI7dn.png',
    u'FAP TV Lesbian': logobase + 'M3LLmt76GGyLBhpAEnRtn368pAeGH3.png',
    u'FAP TV Older': logobase + 'G1L5Qh2QVnSu6zEVua6KOI4hxtUfcn.png',
    u'FAP TV Parody': logobase + 'mu4NIjgq7Xu5nt32zTSxGvBOfk90xt.png',
    u'FAP TV Pissing': logobase + '3QJ9sSAI90ALizvl1B2sbt8WxIVLSu.png',
    u'FAP TV Shemale': logobase + 'd5ulbooZicKw3aMLwn2Ho0yD9c46T2.png',
    u'FAP TV Teaching': logobase + '3MzvfwDLSX8zUmmuO7TpS8O2iD03Tj.png',
    u'FAP TV Teens': logobase + '7Z9gyzosm1oUC82aFfA3mBG9YAjOrS.png',
    u'FAP TV Trans': logobase + '05P2Z8lWWIgaEmvWcTRO1R9F0lMPZL.png',
    u'FAP TV UHD 4K': logobase + 'KQVEqKIbhFV4qblpqG9GTbcebQmqoq.png',
    u'Fashion One 4K': logobase + '8wmOl2MeURbVG7BBYTpL8mlPNh3ZPu.png',
    u'Fashion One HD': logobase + 'iPs2ptiBXm8h0KSnRmyqu45texHNig.png',
    u'Fashion TV': logobase + 'PSjqabjhYIBqcS8hUA8WNrZEjV4zZY.png',
    u'Fashion TV HD': logobase + 'z6q34MCsDCntK8jbJXp4pBQiPlIiNx.png',
    u'FashionBox': logobase + 'bkAp3IW4mLuZ7h3TZU1lydFK0qcq3z.png',
    u'Fast and FunBox': logobase + '4kTNlvE9lNXRfmCUmVn7KdvLVVjenM.png',
    u'Fast and FunBox HD': logobase + 'uHszcvbUgbSFZXBJrInR8iVjilXn3h.png',
    u'FightBox': logobase + 'ZVgchW3kwKCwCxdHUUuaqidpOWWaTQ.png',
    u'FightBox HD': logobase + 'yHhrCaxVKj63WBqu87UfKGnfqviLqy.png',
    u'Fil TV': logobase + 'MZiAclXc11Vxv76evUEhhGOl9OgIS7.png',
    u'FilmBox': logobase + 'EIMXhIxa6RaK3IISZwLgofm63f4oGl.png',
    u'FilmBox Action': logobase + 'nICsCNsae7ulDVVpBUxW7NrBDU7UfJ.png',
    u'FilmBox Arthouse': logobase + 'WlFL9kHfpmhUTdmtxJ0VrTPuDZffTO.png',
    u'FilmBox Arthouse Rus': logobase + 'D8VwB0VlPOQLuDdBh5QaX3rz0dssZk.png',
    u'FilmBox Family': logobase + 'z85ykci0a6q0R9cNljGJn9njZH2EUn.png',
    u'Filmbox Premium Polska': logobase + 'wZDsk1rGT7wL2SYxgy3v5wtRHMpodm.png',
    u'FilmUADrama': logobase + '4if1JzkJbdnQJeg2fovCkCCMOeg1qm.png',
    u'FilmUADrama HD': logobase + 'fWGkWZarY98h18LXSQwHmSAZNXhZW4.png',
    u'Fine Living': logobase + '22I1fK1aMCUgeYUCV0K3vwmlJKELZD.png',
    u'Fix HD': logobase + 'I46bqwVW3Tre1iIxJdvzzJX17fA88n.png',
    u'FMItalia TV': logobase + 'iFjMGbjARNMcfXqCZ638w2ZO7PB1k1.png',
    u'Fokus TV': logobase + 'txtZD7XAiiIdoGtP02oK9Qzqe6wkGW.png',
    u'Food Network': logobase + 'W68LEGlOOMPtN0qoGXvdkWhHBjKet6.png',
    u'Fox': logobase + 'XGC77wQNeEyaJ2z2mDipyIPsoF0xc1.png',
    u'Fox HD': logobase + 'Pl8S60EJ52htHxi1gAw1SS1y8i1p3z.png',
    u'Fox Life': logobase + 'rkksGUl3DstQSEyT26Q07hNCEwyNnd.png',
    u'Fox Life HD': logobase + 'Vou521VpOGAGqhp4HUfiG7BSbKNSk6.png',
    u'France 24': logobase + 'pViXgcMjLnB5WyOoQJ7sBxhHo5fTSB.png',
    u'French Lovеr TV': logobase + 'oEM3QArqYHXMQusqvIcqWOJM79EVZ2.png',
    u'Fresh TV': logobase + 'WFEn5ZIfD8tc9C3Jg7BeaH98DkFCMu.png',
    u'Fuel TV HD (ENG)': logobase + 'I8V5StDnTNHRpnz1wyIstqrjAoIpxN.png',
    u'Galaxy TV': logobase + 'pU2NsRP9CVtEgQuDTi9jcTYV8iAD4a.png',
    u'Game Show': logobase + 'Uc9sBHj0DAYzfXMZmdxeriCBZvUpeb.png',
    u'Game Show HD': logobase + 'x8rAmyXyw8Alq0OKwV9d8iB56lVxRn.png',
    u'GDS TV': logobase + 'hy9yY5tLxmUaLW9tiFzPfKDF9kmorz.png',
    u'Glazella 3D': logobase + '41sniOFmR25QKJ0jHNzpU9qXqo0ewM.png',
    u'Glazella HD': logobase + 'W1eV8FZ8q8mE51fADlfKGYA0LId7H5.png',
    u'GlobalStar TV': logobase + 'Y4kNxgbAnPGCt753P73NzCIbcNz5lD.png',
    u'God TV UK': logobase + 'rn7BFePvaaFWcq8q29kqYxzlAXMXBY.png',
    u'Golf Channel Polska HD': logobase + 'SauXg871tCZXPcP7in8STwwgblGJGF.png',
    u'Gulli Girl': logobase + '2IynBdmw3mmdXt01r8DXKxeor7STnw.png',
    u'H2 HD (Polska)': logobase + 'hiPhHUtTl5Anl2wGGxIwZaDZCclcUB.png',
    u'HardLife TV': logobase + 'fHPc5oaRdIzKpHTqBFnHA4O2LVf91D.png',
    u'HBO 2 HD (Polska)': logobase + 'Hos23DbnQUblEr53FhEJcV0iGAG1S6.png',
    u'HBO 3 HD (Polska)': logobase + 't1vX7k3TcdHwnZUsPSykRKeYD1FnWb.png',
    u'HD FASHION UA': logobase + '1HDP1X4Ohu9mPxietnOgfkP5lz9NIP.png',
    u'HD Life': logobase + 'jUteUS0xRGdvLyBVqNjowEUDkOjT0t.png',
    u'HD Media': logobase + 'woAI3zcytfbyiX0LBRToKzErJNy1qF.png',
    u'History Channel': logobase + '9cVifexiWW0qWDhhpnLNVydoZkeRqZ.png',
    u'History Channel Europe': logobase + 'mXy2qeIvaTSKUc6j4ygG6y69PxGHmN.png',
    u'History Channel HD': logobase + 'VFgU260pmiIyPxCzD3f8R7Yc6DXClH.png',
    u'Hit Channel (Орск)': logobase + 'TVABF4bANYDaoSJwF3rJq2CivaXpaD.png',
    u'HiT Music Channel': logobase + 'n7tghbIGAAh8cyWe7Li0E2iNEJSqkl.png',
    u'HIT TV': logobase + 'b1eHcYwT4UXzC1h3deYy5j11LGAaCq.png',
    u'HIТV HD': logobase + 'rx6sjyAVpjkYDNPEwX5XksWyxx5mVg.png',
    u'Home 4K': logobase + '6qRhgpxNf4ouR4E9Ri7wE6zaJkHc37.png',
    u'HSE 24 Extra': logobase + 'wAnB7nthb9ulxF0lTdAjSuwPSzZfdz.png',
    u'Hustler HD': logobase + 'LBz8ia8AASewVuLjMs5v4MDiVYfsJO.png',
    u'IB3 TV': logobase + 'RPYmEJghA7sVIdLviHrtQ72IAXjUBv.png',
    u'Iberia TV': logobase + 'zOHLuMOxd98YM3DXVOr6x401vlBBxS.png',
    u'Ictimai TV': logobase + 'ZmaCtOnZqcLQSVsYiykJUwcfzEnglc.png',
    u'ICTV': logobase + 'YuNtYxhj9vqgTU9kVuz9imhqviY4PZ.png',
    u'ID Fashion UA HD': logobase + 'vij3fzyJLedFaGr8Ziez2lEuQ3vbIi.png',
    u'ID Xtra': logobase + 'fq3ovkZeu4R4YVYt1VMZN1NU7mMrH9.png',
    u'Ideal World': logobase + 'BD9bMdYWVrltBi9tUEaPbK0ysvEZ5z.png',
    u'Idman TV': logobase + 'UhhUZdtM7FjDFbmoleWalj7tp6nj5o.png',
    u'ILand (Israel)': logobase + 'hFB5pegXEEa6wmbDSi8hljiDjyG7mZ.png',
    u'Imedi TV HD (Georgia)': logobase + 'tAgfgCBlDxsM4yrl8uCAsLNAby90hh.png',
    u'In Life BG': logobase + 'exDoqfMz2p6dw56LttIJUXtKQNoFxp.png',
    u'InterAz': logobase + 'rdntbmpYEYtyRbW3nGa1FUNZPXF53O.png',
    u'Ionian Channel (Greece)': logobase + '58PQSVvURIooy9wXR8bDOiciKHIKFh.png',
    u'Islam Channel': logobase + 'XqP875iZVDQXcyNB4AnAEZ4n3PX9xs.png',
    u'Jasmin TV': logobase + 'MBRUFcRx5wtHLZmgahvcGdXB2ERdst.png',
    u'Jewellery Maker': logobase + 'P3YFOHfFJhUkYesWZKkBTj942AnDtJ.png',
    u'JimJam': logobase + 'BPDFCK5SQF3mXu5MsDNSdtvz4Gjawo.png',
    u'JML Direct Shop': logobase + 'IeKD7u6S0yMzq6kVk9EcrNrJxYCmJM.png',
    u'JOJ FAMILY HD': logobase + 'wAG71KYSSylx2QqnU12Mk1Mn5xFfJD.png',
    u'JOJ HD': logobase + 'turIHyTv0aCVHUK41dfcITUTLmi1Va.png',
    u'JOJ PLUS HD': logobase + 'YqWy1N0abL0URfP9wJOpzplJRKN4iP.png',
    u'Kabbalah TV': logobase + 'IsNgYDg9N29xErIqT01pYtCSkmjvqy.png',
    u'Kahkeshan TV': logobase + '3FgOIcQCth6qBQHBdewbc2RlWs7RfM.png',
    u'Kan 11 (Israel)': logobase + 'VFb8B9pJKvLg0ftP3uhH8saVm2HvxA.png',
    u'Kanal 10 Asia': logobase + 'I0pSFVhG3ETBqW4dO0syl6z6pDhH43.png',
    u'Kanal 10 Norge': logobase + 'fGCKm0tjHnBkw9Zf2AIr83h6ESy6LW.png',
    u'Kanal 10 Sweden': logobase + '0Szl3uzJAc0IJKDcDHxMt2Y9Js6dcv.png',
    u'Kanal 11 (Estonia)': logobase + 'H5d4DqR5flnZzDLiCL0OETyuHKogUy.png',
    u'Kanal 9 (Sweden)': logobase + 'DWj2wxyFA9znTvzk5Sd1fDduDvgHAW.png',
    u'Kanal D (Turkey)': logobase + 'BfqPc0uOcyvpa7to632VkGRXB4LPUp.png',
    u'Kanals 2 (Latvia)': logobase + 'uC5SXR78b5FZQL49POK7djigk8rWh8.png',
    u'Kanаl 2': logobase + 'rEuErsoVICOvz7v8NqQU1XM0S1K9Qw.png',
    u'Kavkasia TV': logobase + 'VvWW2WX6PQNuUYsb68UF3hOggdnWRY.png',
    u'KazSport': logobase + 'Gq7Ux2KnFiJevqPv8TZkTZeOZX0G2B.png',
    u'KBS World HD': logobase + 'OkjNOqg5N6zJ6bJ9oggy3QbKqwdIow.png',
    u'Kids TV': logobase + 'MfjpBLPvzcqUnCrMq0pfVBYYWcgbzK.png',
    u'Kidzone': logobase + 'pcMnPzCKzvWdNKMTbdjqmniTNImWXF.png',
    u'KiKa': logobase + 'yk4qy13mr41b8gtHhtWOlMpI4cUaTB.png',
    u'Kino Polska Muzyka': logobase + '6mkgB96JjYh86Y0HWHmwkexG4Cspvq.png',
    u'KinoTV Polska': logobase + '9tgeaMFg7ZAwvZzsWma3p3ulwjpWtd.png',
    u'Klipkar TV': logobase + 'YkzWrmProzzCAqvGM8fMh74LkvjvGl.png',
    u'Kokshe (KZ)': logobase + 'GAy9yVevq01QFM1tC7qw4T5afFEBF2.png',
    u'KRAL TV HD (Turkey)': logobase + 'kMwx0JwBvArG7SLkNkzLpGiWacDwxV.png',
    u'KRAL TV POP HD TURKEY': logobase + 'sPRUTlQ2g4PUqZiNwiageFYrNuTdCW.png',
    u'KRAL TV POP TURKEY': logobase + 'CkY3Qs0wKGVynCahuRDRcgGp4ql5hC.png',
    u'Kratu (Херсон)': logobase + 'y7ZkntjjbSe0bJ8CkdDYRRUts9exhB.png',
    u'KroneHIT TV HD': logobase + '1RwPQHYCYOfdIZ8Zs5HlYYVs5bXoJE.png',
    u'KTV 1': logobase + 'muJoXtMbQUuLzLRQdmJ2E9mkmojSVV.png',
    u'KTV 2': logobase + 'Ww1LuUOEyZM1D51wqwPyA3H4ercXm8.png',
    u'KTV Al Arabi': logobase + '3GwnAR3cGjZnLIrnIcaUMZn7Fff31m.png',
    u'Kultur MD': logobase + 'tdo6j8CCz0dXXXScqqkAYWyx2f2uDb.png',
    u'La 1 (Испания)': logobase + 'rVohjGi0xaYhUu4zLvcAAH6hXDDtR4.png',
    u'La Sexta (Spain)': logobase + 'hfKj3YyJdTcS7Qh8udnMYU0DkXJAQj.png',
    u'La Tele (France)': logobase + 'qHcU6UT7sGbJQLUyeuAQoYFyan3VmZ.png',
    u'Lale': logobase + '99AZ5VwFy9yZrgsdZ6kIxcoYqwSyUH.png',
    u'Lalegul TV (Turkey)': logobase + 'YqY7FVl9KFV02f0OJWs4zao6rYYhmk.png',
    u'Lampsi TV (Greece)': logobase + 'dTcs2ZGjW12dsyoa3oV4RNMnhD8hX0.png',
    u'Lancelot TV (Latino)': logobase + 'SwEWW9sUi5mYATwDgOF8oGXbnae3D4.png',
    u'Leomax': logobase + 'HGm0W3LbxRPeRcgEdYuuBEKp1zJ104.png',
    u'Levante TV': logobase + 'TJ4eta4PMGJifO7tj9n9xEuZ2faqQk.png',
    u'Libya TV': logobase + 'rvRq27Or6K43frtXix2HweerXIguSK.png',
    u'Lider TV': logobase + 'LByLhdeQ30Ln5pSZRYSpoLpXQS5Ytr.png',
    u'Light Channel DE': logobase + 'b3DUwHwxWENo3v5IywSuwtG8CFANZi.png',
    u'Live (Japan)': logobase + 'gltX2kkTNW8UiB0muraNNTOCR38yVc.png',
    u'Livechannel': logobase + '1GefItjnPftC2iBHBjsA18Vx2HMUUU.png',
    u'LOGOS TV': logobase + 'oluCocuAj48uhnulHASOtPFvGphhnv.png',
    u'LON (Nuenen)': logobase + 'kJH7ptKpRVqIKquBXnLdm1qFX0HdMY.png',
    u'London Live': logobase + 'daTdq8l2gxrLCXppatFb2Czv0SVbyK.png',
    u'LOST HD': logobase + 'TvixlXAz03KbVHFFgMRBMQkJR5at2m.png',
    u'LRT KULTURA': logobase + 'iT3NgoFBu7R4wQ0yDQ9WQsMMJQfIh0.png',
    u'LRT Lituanica': logobase + 'SRwS73rXowTlsbzN1f9XsIQfMQGA2A.png',
    u'LTV 1': logobase + 'Dw5UZOOz3g472ueIHuupz1mX1REWrU.png',
    u'LTV World': logobase + 'Nz50U95YTRgQxm8v7H1xB2SJCeKCIN.png',
    u'Luxury World': logobase + 'zRHfsEZDaXLvRsYLpHOJzYWXEyeMOx.png',
    u'Lviv TV': logobase + 'VMl4S9yd5IYFAVFaR8XG6KEm5pgVu4.png',
    u'M-1 Global HD': logobase + 'edye028FM8k27MT0Xw8igifiwsNGkm.png',
    u'M2o TV Music': logobase + 'silsIkmGso1E6vqUb6Ta6y3XHVl7Tu.png',
    u'Mango TV': logobase + 'xOSisiRdW6w9bDh194GL7lSvnkBDa5.png',
    u'Marao TV (Georgia)': logobase + 'LBlYAbEi0nPlw59dc9nIa2mLLGJRkK.png',
    u'MaTele': logobase + 'Q0B2mCQJ5632OvzZMItGxvFMiM2VJw.png',
    u'Maxxi-TV': logobase + 'uqyYr07PPk2OuEdnNrbkMHVlGZCJp5.png',
    u'MCM Top': logobase + 'b4SLIxXFbKUErZxBXfGoo6eQN5Mu38.png',
    u'Medeniyyet TV': logobase + 'XR7iGmXKFiVyK0D5tfhp97qaHd7irC.png',
    u'MediaShop': logobase + 'lNWjv4BKLhSI4ahyWQGCV5mHqTIcX1.png',
    u'Mega ESP HD': logobase + 'zxQ5jbELSVo23z65yyH5Um0JpKZWQt.png',
    u'Melilla TV': logobase + 'NusuNYJEzHjQpTGkTncflNnMmSj6uh.png',
    u'Metro': logobase + 'ssgI9qDinPuyUI7ImJTIFYhPXZTr8i.png',
    u'Mezzo': logobase + 'GUzJ4cyK50ZahOSIx6tTbwGLJiUnSA.png',
    u'Mezzo Live HD': logobase + 'lGOtRiUoGyJUMCtAtUwevBerpQORD4.png',
    u'MGM HD': logobase + 'o4K0lgc2D1GkuFwMC3Cdg1uK6fMrG4.png',
    u'Mi Lady': logobase + 'Fd556PD2ffD6zdVUiX0dvVfBJavBNd.png',
    u'Milliy TV': logobase + 'OZvykYUX9UnUWpYPGQBZZ6yGdnsyET.png',
    u'MM TV BULGARIA': logobase + 'gcbiPfLUfTs2YwuJcNm9m0Xtz5Ttnc.png',
    u'Moldova 1': logobase + 'ICjWgPo5bbLh2HPFQ23O9FUpcIRH2k.png',
    u'Moldova 2': logobase + 'CVzwTJQ2ekczontASdl0FPTrxl3LQL.png',
    u'Most Video 1 (Украина)': logobase + '0ePynk8TTCMB4qV4EmHzDfPP1dgbM1.png',
    u'Movee4U Chicago': logobase + 'KRKa4VK8caWx982pSMzEn0GQvOOCCw.png',
    u'Movies4Men': logobase + 'WOMhUah3sPwZIJLja4TsJrdJlkrtFF.png',
    u'Movies4Men (+1)': logobase + 'PnKBdCiEXXKkcW4BpqcVKLLbJQP2Wn.png',
    u'MSNBC HD': logobase + 'c16UWsPglT82lDIWRKM4dOcOZ4kulT.png',
    u'MTA International': logobase + 'BFAeZ7QK9z6OF2uVWOkGfvjU43CIId.png',
    u'MTM': logobase + 'QsrNwBeOW8SKELFvFl9pDz2HswZiQL.png',
    u'MTT Trnava': logobase + 'QtJUR28i7OKo7Rx4vf8n0qUZR8E9WG.png',
    u'MTV (AZ)': logobase + 'smH9QwQIzcNLg6bmabpOi3CzwtwvYh.png',
    u'MTV (Norg)': logobase + 'WkHV1YUJngmqeEuX1r81lM4uauC64B.png',
    u'MTV Dance': logobase + 'ZXKNRw6Ai8u4lY0wxeycQwj2dIkm66.png',
    u'MTV Hits': logobase + 'iLJhuLh9kFLQkG4ERvLGSjSgMfNiM4.png',
    u'MTV Lebanon': logobase + '4inIqsqTGNAi8BNsxQ7rsUjrPrlyIc.png',
    u'MTV Live HD': logobase + 'WjyYXtYHhG5COxGab7luHb1bmvAioA.png',
    u'MTV Rocks': logobase + 'SEwn7rL2FxPcf5Ol9KRKedIwXlpsAP.png',
    u'MTV Россия': logobase + 'P5ijp2sRQsKVZkOJwjdqIVgYdJzhpZ.png',
    u'MTV Россия HD': logobase + 'YOE9yEg2KwmItjHwMHcQDVvIMsfOTg.png',
    u'MULTIKTV (Greece)': logobase + 'RnmusEQVtZux4lfd3VIxuGiQIhpd6O.png',
    u'Munchen TV': logobase + 'dEIDrD6sbyiTRRaRwlu4sSCpIIATnP.png',
    u'Music Box Gold': logobase + 'fvt4pris0lwnVhSyUrh8QlyzWBhbgz.png',
    u'Music Box RU': logobase + 'zaHCW7nPCyGRnqHDkenCIXo7d6vR7v.png',
    u'Music Box RU HD': logobase + 'CbPggS9SpKMrgFW5myDvhLEFvm0hwp.png',
    u'Music Box UA': logobase + '8T7Rnct8q2VHhRm0BcGFxCjxuYEArc.png',
    u'Music Box UA HD': logobase + 'huXVI1yxMaaWbgsNGJEq8aHhbck0Yi.png',
    u'Music Choice': logobase + 'v95BoT0BxSmrqNYAr6qagQQMNb34ih.png',
    u'Music Choice 90s': logobase + 'VlQO5jawTo59lQ7R0LjPagT1xk0UzO.png',
    u'Music Choice Alternative': logobase + 'napjkROfGrYGKcTNioRsVCMq8GdoPJ.png',
    u'Music Choice Brits Hits': logobase + 'l6yqeQsu2OZrbj3ebY5vr0lSQ9N70C.png',
    u'Music Choice Dance EDM': logobase + '1qttT7tkDx2WhUxH8AZAr9rJmSiZb0.png',
    u'Music Choice HIP HOP  RanB': logobase + '7RfelixrNWQZIPwe3fXrMiH7qS6q4C.png',
    u'Music Choice Hit List': logobase + 'jeucueOkDiS7mMOSSweDA5xPZXf1hd.png',
    u'Music Choice INDIE': logobase + 'MK2kN6a4Lc0CXHdWyZ7zxfpvLXvqqN.png',
    u'Music Choice KIDS ONLY': logobase + 'ovHnjmwiEgGLDGFr6DaTZb5rwUTcJJ.png',
    u'Music Choice METAL': logobase + 'TF8Sre9bwBQMML5moIUX8Em3ezuTvJ.png',
    u'Music Choice Mexicana': logobase + '1sty7nuOhEBPx0fpxCqiqMY0rrWoCP.png',
    u'Music Choice MUSICA URBANA': logobase + '1IHnwTpIisw39uG0UPGxx3pR2ctQds.png',
    u'Music Choice Pop  Country': logobase + 'ctNySuvL3dEFgXqJQe413jgZoAqQES.png',
    u'Music Choice Pop Hits': logobase + 'sL2Il3NXGTRStCY87IZsRWVHbqexDN.png',
    u'Music Choice POP LATINO': logobase + 'XoT56dAuwYs415pOqYqEtPnmtTnK6s.png',
    u'Music Choice RanB SOUL': logobase + 'UgXWpGFes2eKbKS49LMg49ghvssDeV.png',
    u'Music Choice Rap': logobase + '15u7PLuIUwUeyW5FnaQQrSI5JVyCwr.png',
    u'Music Choice ROCK': logobase + 'iEcUuvGYX1IHoI90HpyPxPMFEYtiaS.png',
    u'Music Choice Teen Beats': logobase + 'X4ywLZygV7ZAy0pgXG1e7rB5sMmw2B.png',
    u'Music Choice Today': logobase + 'k9fiBpddNvSgEwqoLT1Ft0bUOFDB9u.png',
    u'Music Choice Toddler Tunes': logobase + '9RXCPaFaXTdVlAVNRql6bmlMvPk61S.png',
    u'Music Choice Tropicales': logobase + 'dPEB04nOVSmPYhBpNUV4lXI5AStacH.png',
    u'Music Choice Y2K': logobase + 'tepRMISYeUwMT2etOv1ORWFMPft8Y4.png',
    u'Music Choice Y2K RAP': logobase + 'vjA51aiIXEE321BF70GMv9m1kTktbz.png',
    u'Mute 3D': logobase + 'Ck3p0UDLrkbStG8lYHF5u4oFm2tXTd.png',
    u'Mute HD': logobase + 'nr009UxTZ2qpOSfKjObdU348PqW94O.png',
    u'MuzzOne': logobase + 'Ft5ACI2oTWf7cEr5oWuPkigDzP8nGb.png',
    u'MyНits': logobase + 'oJBfETNJVIgnWCDGToxSMwKtYajz8p.png',
    u'N-TV': logobase + 'br4clcRCC76Vm1wDOaUchlNTVrpjXH.png',
    u'N24 Austria': logobase + 'aQjAnNNoEEtgaFuBFQkBSfh8A5kwlX.png',
    u'N24 Doku': logobase + 'eq9YvFYrrALYxVCZJfAkVGowMr0BWS.png',
    u'N4 TV': logobase + 'R1NDSrUKnB1RoT8iv1okSe2xY39W4J.png',
    u'Nano HD': logobase + 'VZ3FQUDbk4FSdqegZdiaK9frpumHmk.png',
    u'Nat Geo Wild': logobase + 'ciHIDUuHEnkEuPghbcqkDQx4vadle3.png',
    u'Nat Geo Wild HD': logobase + 'YYa1wyNA9prFK1APZ2ZSHGirPpm8kY.png',
    u'National Geographic': logobase + 'i6STSw6Hg1wWP18yBAOyKoKpSMeKLu.png',
    u'National Geographic Abu Dhabi HD': logobase + 'pRXifqzhHWiGqbm4zTjKVAWEwZomL8.png',
    u'National Geographic HD': logobase + 'hK1waimMq9eAp0ugM19moSoQvUeve5.png',
    u'National Geographic Polska': logobase + 'PtoKR0FVbCGRB6wTO24AOlKaW3UxEP.png',
    u'NDTV 24x7': logobase + 'De0lld8mAE6SwWjpsAr0EyVNQ7oEbt.png',
    u'NEBISET TV': logobase + 'bugOHtRHyF9Nx5ba50Eyf547mn8kS1.png',
    u'Neox TV (Spain)': logobase + '78cCkRIZXPdIcuFXsYlxHrOon892FS.png',
    u'NeTV Toronto (Greece)': logobase + 'DVBmwrVVGBB7qosqfjtfshrN6P4w1s.png',
    u'New Generation (Greece)': logobase + 'TCcVvNNTmEyR7gCpcntlnaE6wUxqI0.png',
    u'News 24 (Japan)': logobase + 'Pevzo5Jt8sxSvsKHFRjo2crwXqkTba.png',
    u'News Network': logobase + 'puoOIFeHu3ojMldKVG7VVObJji589p.png',
    u'News One': logobase + 'SnaQqBa1YMS2b8b8EGdZSMCConLbDS.png',
    u'News One HD': logobase + 'jlgF3yZBnmiBKmYCa20SmajQmPqqYQ.png',
    u'Newsmax TV': logobase + 'qVDjJCQ1bdoS4ERF3WPgJP7K8XNdR5.png',
    u'NEX TV (Spain)': logobase + 'VYUqimAzc80yN7d8uaOvX6FoyKikBM.png',
    u'NFL Now': logobase + '0kIhLlfYvugeCvSgRx22lnnTU2TT0c.png',
    u'NHK World TV': logobase + 'JJ8Sh9c7zA3PaXlK1ZaNjy3GgWQFh2.png',
    u'Nick Austria': logobase + 'WIGRX4su85Ctmhn1P9hLgjVRNLzVyd.png',
    u'Nick Jr.': logobase + 'D87kJ3fIWIm5wKi5qxm24nbuPQv0U8.png',
    u'Nick Music': logobase + 'ncKVjI3fRgYSlpUfTudc5k0VNXMaRi.png',
    u'Nickelodeon': logobase + 'j66xpaZbfiYIgQxv76QAPckPVjmLNs.png',
    u'Nickelodeon HD': logobase + 'CFYx7Bd1aDSgkqjMLLQjFE6xe3u1E0.png',
    u'NickToons': logobase + 'qpwGtgmnGqFKGMW8hz3zuDfMMUjI7f.png',
    u'Noa 4 HD (Germany)': logobase + 'lUK2bbV2YsbEvwVkgXhkos4MuNhxfh.png',
    u'Nobel TV (Днепр)': logobase + 'P6DAbIQFdg20dEgltDhUUXSyaMgsJZ.png',
    u'NOE TV': logobase + '8YAdB9BsnCltbSisD4gRyuWiKGzLcM.png',
    u'Nova (Spain)': logobase + 'PaVRBWtRbjYKQTf2S6dmmFtsNzHpkf.png',
    u'NOVA TV (Bulgaria)': logobase + 'tCQD0L4JrWuec8fip6PrwUSVMIejZ2.png',
    u'NR1': logobase + 'WTCzIDTnoSivAudx3oL1nZMRSWJP48.png',
    u'NRB Network': logobase + 'uiqarDf50hZ4z89q31R0L5yZm7ysjo.png',
    u'NRJ Hits TV': logobase + 'aA0QJTWWcNxtgthZlCDqG2Ja8OvxSR.png',
    u'NRJ TV HD': logobase + '4BplmiqNJsDS50xEOephgAMgh7Tsqj.png',
    u'NRK 1': logobase + 'OkM2OWgOHATFS1mdCaJQ1VJ9Wut27i.png',
    u'Nrwision HD': logobase + 'EOWUjtgtScEpvpFhEACdR3Dtc3nHqU.png',
    u'NTD TV': logobase + 'iy4LZ8PlkstKJ2uuyIELVMuCSz5yEy.png',
    u'NTV TURKIYE HD': logobase + 'UHAOD9j1WxvQhXbLwqwHUpsI44ka0w.png',
    u'Nuart TV': logobase + 'aqMIuUixqLQYmJITPnOGtFkRPuTqKa.png',
    u'O-la-la': logobase + '7ddvb8Tivq7yuEgffrKildHi2BQcCE.png',
    u'O-TV': logobase + 'UlIt4rE3FZs7IQmPN3tsGS6fqY5F1D.png',
    u'Obieqtivi TV': logobase + 'gthZWOanhxLhjH3YZzqlkFMwwpNAI8.png',
    u'OBN': logobase + 'p0LQ9JvFiUMrGNXIwxySFfIFkFzYfa.png',
    u'Ocean-TV': logobase + 'cvBAngU16nJU1bEzxAEcMPiPvf7fVT.png',
    u'Ocko Expres': logobase + 'xh9xvE50KtXueT6WGZt7QBWZk7y0uL.png',
    u'Ocko Star': logobase + 'Z9gVKumWFjtZKSu8yZ4jSeIUERJtBB.png',
    u'Ocko TV': logobase + 'GRn2qo7rOMBDzPPSBdF1NaWsLPEtbd.png',
    u'Oe24 TV': logobase + 'pRYc66iCYsaziRLLhGq3oitnnPq2BD.png',
    u'Okto TV': logobase + 'GK3AaVPYTkRNqrXGUje5oxN4VZwBsu.png',
    u'Olive TV': logobase + 'h9uh73Zm6vaOWhiOdKqL2f1O9pHiJ3.png',
    u'Olympic Channel HD': logobase + 'f0D2GjnkvNWNCYZHuzDTILKLgzjjWa.png',
    u'Omroep Gelderland': logobase + 'plxNL7YOWhKg61jlCvOUO3ZzRGdLB0.png',
    u'Omroep Zeeland': logobase + '82EdWoiOYEBkH3oLT14d5mMRHJf5F7.png',
    u'Omrop Fryslan (HL)': logobase + 'lO7Bpo9O2sap1tslyWF50gDW0HKPBj.png',
    u'ON TV': logobase + 'iiFKUuGRAbCX5CjEysABAXo1I0wKW0.png',
    u'One HD Deutschland': logobase + 'SpikhOGt1aj8hFK6rLPnKroMwHBU6U.png',
    u'Ora News': logobase + 'fYPqYw1QNRMb12E2rNvs4w0HGKR2fe.png',
    u'Orient News (Arabic)': logobase + 'xddvwXoldgJdPmeyQgkMwUqnXth9oU.png',
    u'Outdoor Channel': logobase + 'SuxFoocUmay5G8jtfJaHL1yIbAT5Hr.png',
    u'Outdoor Channel HD': logobase + 'SuxFoocUmay5G8jtfJaHL1yIbAT5Hr.png',
    u'Paramount Channel': logobase + 'Iyzjhb5BBRKfvEZdBwNJ785jzroODU.png',
    u'Paramount Comedy': logobase + '5EtvAWXB7VK1Yw82yvO28sY28dU4ZC.png',
    u'Paramount Comedy HD (Россия)': logobase + 'tW1iwVwhyJCc0IMabjgHJO0lLxk41D.png',
    u'PassionXXX': logobase + 'U2oO3j1eda31nrTwHqaQ8psrLfH5CD.png',
    u'Peace TV': logobase + '6b4wTEfhrF9cgIjmw2gqL6CNdCcM21.png',
    u'Pearl TV': logobase + 'fkWWQIBBuR1cEYpkg87kpOkgtrYBcC.png',
    u'PGCPS': logobase + 'H1yX03jPQoUFXjIviT7OJlkf9Qo0g0.png',
    u'Phoenix CNE': logobase + '4A3PI1xIjIeECNSMDDvOfwXd5n2sso.png',
    u'Phoenix Marie TV': logobase + 'mC9hfoTbTEXlNXEVFrJvXaj78QGUhA.png',
    u'Pink O TV': logobase + 'aI99kH6bHY5Qt2ph4W1Nh0wxdzd1p8.png',
    u'PLANETA  TV BULGARIA': logobase + 'bk1r1otUWCWjhrSVZGBD1Gn9KJ77VQ.png',
    u'Playboy TV': logobase + 'lIWBxmt5GDl9tg4KsQNtA0CuZWdOHH.png',
    u'Plovdivska Pravoslavna TV': logobase + 'fG99mx79KFgS4DxTuIpAYCuUKL8SAj.png',
    u'Polonia 1': logobase + '3fzUyCBgUoJ6zqc92KSXh9g9utJEuO.png',
    u'Polsat': logobase + 'c9JchVUgkvFPn1yU9iUIZhREOCa2AY.png',
    u'Polsat 2 HD': logobase + 'lvJrqXJ2YfIS5pd4suLfjZSmab64kE.png',
    u'Polsat Cafe HD': logobase + 'ctC0ClSiVKi2ZzhcARQHXehGDZbMTm.png',
    u'Polsat Film': logobase + 'atJULEx4QJTuvN1mvGlFf80aMNOE6v.png',
    u'Polsat HD': logobase + 'q6trwjdw0vcYQ2nmEIde4Yheo2uVkj.png',
    u'Polsat News 2': logobase + 'kqwKovptQrc8kZguLHFZA54JGGaXZ3.png',
    u'Polsat News HD': logobase + 'j02sMeFAKK6TrW1OnodLSTLJmh6PZI.png',
    u'Polsat Play HD': logobase + '5NJU4spT6sZhpMkOkNOJ0V5mHRYHKq.png',
    u'Polsat Sport': logobase + 'BywF4NqOAnWreAWiiX8ohep1YL02oi.png',
    u'Polsat Sport Extra': logobase + 'gkIPn4nGmIrbcw9zSbFBhzXTQFdoyl.png',
    u'PORTALFOXMIX TV': logobase + '2ymsCxNu8UCABlQoGVBqFvSKt52DKY.png',
    u'Power HD': logobase + 'jNidPvKNIFVPyPYyQ1KX51AQp5DpUh.png',
    u'Power TV Polska': logobase + 'BDWO2Y1LbSlEE64ac81QSeFcxqnTDJ.png',
    u'PowerTurk HD': logobase + 'qIT3U0dBMDCp1yjArmWrYPk4QfOE7k.png',
    u'Prime TV': logobase + 'drU0O3vVzB90j5FWJWzTGlQ8fptbhC.png',
    u'Pro TV Chisinau': logobase + 'hT6ocXwfltpDABf9WqBYStjAFk8pyk.png',
    u'Pro Все': logobase + 'OavKhOpBMn27qPDKJXXm5rgATgovgn.png',
    u'Pro100 TV': logobase + 'vKrCCz2GIcAiQygU5lpPHPgpqliRTY.png',
    u'Propeller TV': logobase + 'TTK7x3Eey2cGSgdyRQj5JAlnT6Tkoq.png',
    u'Q Music': logobase + 'upeHUqOfARcxJuTKjGcEoAcKaFPoAX.png',
    u'QTV': logobase + 'zmh1xStjBZGJ6U5g3xLoemD2oT3w3h.png',
    u'QVC Beauty and Style': logobase + 'Zs0jOotZ9DPcV3i8kKUcvUwJmFicH0.png',
    u'QVC Deutschland': logobase + 'cgZkKJwQjioVVuc8DGvv4t7F5UKQjZ.png',
    u'Radio 105 TV': logobase + 'EIGvAtLdXk8pUebkqCbuSA3diZ77to.png',
    u'Radio 51 TV': logobase + 'P3oktFRdHRtqT5D7Z9859zEXOFjpfD.png',
    u'Radio Bruno': logobase + 'TTn2QbP9l0kiIf9YdDkO5tg8dhTtrt.png',
    u'Radio Capital': logobase + 'ChGANaKkVGtrKs7s4WaCnckHoJJ9p3.png',
    u'Radio Catve FM': logobase + 'rhhKmIDgStaBNF0Pvr4oh618Bxk0Sl.png',
    u'Radio Conexion Abierta (IT)': logobase + 'nHah6MBNY0jfZzNgyalBjpjnflV03A.png',
    u'Radio Contact TV': logobase + 'WGGHhJkKf3wOE4eoNoGFz6fSdp3llf.png',
    u'Radio Linea N1 HD': logobase + 'tXouTkHSNaknw0xD6RhE24zac8JgPU.png',
    u'Radio Monte Carlo TV': logobase + '3CiAgachWg7ohgoU1Gilcm73hXhT41.png',
    u'Radio SWR 3': logobase + 'EMfiTewaHJeiEhiYmTLaaAvscKzdCR.png',
    u'Radio Taormina': logobase + '3WyzCie1FSaK9AtAfB4dkmu9UlgKII.png',
    u'Radionorba TV': logobase + 'aF9zJ25RRboA2SRtY5FCjet2tigJ6d.png',
    u'RadioU': logobase + 'QZW4T2hqT7Ko5DtzEHwC4uqMl6G9dh.png',
    u'Rai 1': logobase + 'jTchRtiY0FJ91k1YQxBVHgi0rJ2fJX.png',
    u'Rai 2': logobase + 'NwtqcjZNlE2S71D47e4VQua263z0yw.png',
    u'Rai 3': logobase + 'IpAZDnIoXaiRiteKWVWNRIVFIlf8Sy.png',
    u'Rai 4': logobase + 'XNoaXxn05rFnh6vlH4dNy4Z1F5n1PG.png',
    u'Rai 5': logobase + '9rcUDZHzLhTLGKaMd31XtBKg5Snp2I.png',
    u'Rai Gulp': logobase + '4WnGLyURlZYFt6GPbQSw59hoyBNxPD.png',
    u'Rai Movie': logobase + 'Gp49671OSLSkXkuUG4WIdKJJ4HIHZc.png',
    u'Rai News 24': logobase + 'CXDYq1FWPBJgCMUXcOmmfSA4hff9qe.png',
    u'Rai Premium': logobase + 'cIruVk2ubcr88D6nywWwF4M0a9kEah.png',
    u'Rai Scuola': logobase + 'K2D7bj49TZpyf0BIeTJbexYiTixA07.png',
    u'Rai Sport': logobase + 'z7vGsy7xfKxJmSV9I42AUIwQ7PMZA4.png',
    u'Rai Storia': logobase + 'jLpVQcJBOSLCKIBsWl5GhPq2MPNIOT.png',
    u'Rai Yoyo': logobase + 'zOpKuw0Bkk7b57vAjeBEbEUMVHPzob.png',
    u'RaiNews 24': logobase + 'lSQGWWO5EgBMQYSzctZ6551jifnl8z.png',
    u'Ran 1 TV (Germany)': logobase + 'Tblv47NQvFoSzh4Z8QaYiCt7OmYCvk.png',
    u'Real Madrid TV': logobase + 'KfoLG7goywcRhMMCc3sO8IVwhuATLp.png',
    u'Real Madrid TV (Испания)': logobase + 'ENjYPjd2gZlbo0Zew3NVzZZJFmh3pC.png',
    u'Red Bull TV': logobase + 'ob4ETM827NiD1tnEDrvZXzAv7yXygj.png',
    u'Rede Seculo 21': logobase + 'LTqAsTrS3hwVdE2md81Skr7ntssAyg.png',
    u'Redlight HD': logobase + '5tFZcJtKAZRbXtKGDuLe8FZ3lK9LI5.png',
    u'RENOME+': logobase + 'PhujKX6HEppxw5O5NNmASNrDNy32ih.png',
    u'Retro Music TV': logobase + 'zVS9G1oine56udlAK30gNut16iJ9Ft.png',
    u'Revelation TV': logobase + 'gK8K5dIwNW8YqrGZCilO42UX0NF03i.png',
    u'Ribera TV (Spain)': logobase + 'ca8QOEtBTBMLOZBhzMMAmFxSrFkMOD.png',
    u'RIGA 24 TV  (Latvia)': logobase + 'NxpHdvmoFLf4hT6VDHNVieZ6oYKkII.png',
    u'Rock Nacional': logobase + 'fHYn3Ar4WyP3MdIyrfAM01MOGimazO.png',
    u'Roma TV Bulgaria': logobase + 'Nn8hYbYGZsJFqzTDGJ5Vj0OgTtHzon.png',
    u'RTG HD': logobase + 'g4MDyw0yqXWkIar8eH0cgCz4xhiKON.png',
    u'RTG International': logobase + 'oUhBjdbQ3NCvoQETKvxNQbIysei82b.png',
    u'RTG TV': logobase + 'IeaOjwR6Q9eJjGZr0LYk2tpchM3ITZ.png',
    u'RTI': logobase + 'L9QC9Vq6wXNGCQcQwLqxRymuwnYP4w.png',
    u'RTL': logobase + 'TPx8W2LGlOJDLO2luYrgL2ujOyHKKV.png',
    u'RTL 102.5 TV': logobase + 'bMHYTBt1vlQJnBjJ4CE40Y7PtOZ9eu.png',
    u'RTL 2 Austria': logobase + '49Zk8oImqj1HODb9RNXNt7ZzwobSNv.png',
    u'RTL 2 Deutschland': logobase + 'IKo2k4CAhNSDOsJsjn73YOWkXLDNjd.png',
    u'RTL Austria': logobase + 'EHn59YnNVoIeuqT3Kd0dWNgnGGcxi6.png',
    u'RTL Nitro': logobase + '8urdZv4ht1jKOX0O3KGn3Pk4GNzuvg.png',
    u'RTL Switzerland': logobase + 'SzqPulTovz5fMhYYNXl14t6y9fUbOe.png',
    u'RTL West': logobase + 'twHjduxMSkuETTSoyw3n7kwp9wpNry.png',
    u'RTLplus Deutschland': logobase + 'JQ899LldgDEV5N1ku0AbQJxkd9dmyE.png',
    u'RTPA Asturias': logobase + '6fWovUyPwrqY87wy95cV0AdDMUc0ZD.png',
    u'RTV Drenthe': logobase + 'RVeRQMHPxpl2ZTrM3HjQesBlkpfRP8.png',
    u'RtvCE (Italia)': logobase + 'OtMHxeQFBAxNvM85dzJysEBZf1YBKv.png',
    u'RTVI': logobase + '762hoLsS7ZqvPckokrxKmyER4QY2TX.png',
    u'RU TV': logobase + '161.png',
    u'RU TV HD': logobase + 'YiMEY6LT8ePoGhXJ7lKz7Os4hY3DOP.png',
    u'Russia Today': logobase + 'rL14fwCe8q10mKTchOwLkfwQVki9XK.png',
    u'Russia Today Arabic': logobase + 'OPbYfpQc4ShP8JmgPeiavUroY98H8L.png',
    u'Russia Today Doc HD': logobase + 'b8QePfFi6zsCDS7hfTeFWES5UN4SAk.png',
    u'Russia Today Doc.': logobase + 'VOYx5PIhDPrWiZIcCYpm1xrDSQZnsN.png',
    u'Russia Today Espanol': logobase + 'zkPwjfFbktNO8EYDaHlYhwAeT88dmY.png',
    u'Russia Today HD': logobase + 'rL14fwCe8q10mKTchOwLkfwQVki9XK.png',
    u'Satisfaction HD': logobase + 'isdNgbfGENuaDPSMzsz8WMjBzc1rah.png',
    u'SBN International': logobase + 'PqgmJNT0zrBVSCsRoGYT91pr9y3Bqf.png',
    u'SciFi Universal': logobase + 'HtJ6UUUl9zFFP0XcgHfuNjbCFatTVz.png',
    u'SCT': logobase + 'bDRN0guXHaNHruxtyFkpKYz8J09Xj3.png',
    u'Semerkand HD': logobase + 'f7Ynxa6KLwY20VXf6DGRNtsGAVstrv.png',
    u'SENAL PROVINCIAL': logobase + 'uMIP1pib3fYMEl3R0bZNhCZXeJZrq5.png',
    u'Senato TV (Spain)': logobase + 'zrDVQ4JpjR4S2xAVWEnwkaYYCNxL9z.png',
    u'SET': logobase + 'tKzOKIcOQYrFl1VL8B0QqERFXCAYfU.png',
    u'SET HD': logobase + 'sX1unYoKj8JR7m8lbtkmPCClRrjAZ9.png',
    u'Setanta Sports Eurasia HD': logobase + 'dymcOtdEXaz0oHhdqY2ytn7CEAUfnL.png',
    u'Setanta Sports+ Eurasia HD': logobase + 'fd3a4zJT3IJcTWP5daxp5yUIYci9YN.png',
    u'Sextosenso': logobase + 'HXMvFMLO9weHUcolVmmMKpz98T0K4K.png',
    u'SGDF 24': logobase + 'zgX83hMJYukAhttCXvDa12o959Mt82.png',
    u'Shant Premium HD': logobase + '2CmRmYOEq9RADmLInEL28WVzdgvYnu.png',
    u'Shant TV Armenia': logobase + 'elW3X6Sq5hY9atbDtUvaUJmqRNrpbe.png',
    u'SharjahTV (Arabic)': logobase + 'N6nKkznzWy4QPM84xqVwxTjT7fwUDH.png',
    u'Shop and Show': logobase + '7NlIUTEOE8fvLFVxXCRqpYzhuuSMmB.png',
    u'Shop Channel Japan': logobase + 'qFFONLuSwrWqAacMl4sx01GL9K4Y3O.png',
    u'Shop24': logobase + 'bCuxLyvoTk8l5cBRSyKFXjWjYucvlu.png',
    u'Shop24Direct': logobase + 'IJXasbAQtMs61oK3i6A83XClUjaOLJ.png',
    u'Shopping Live': logobase + 'HVwxC489SYFr8Ttqs1he9RZjEmJjPn.png',
    u'Shopping TV': logobase + 'Yhipu86vXMGf0hxCTXLezpGpcUbibW.png',
    u'Showcase': logobase + 'Spj04CxOgc79FdH9W739kj6NQ4gGCx.png',
    u'Silence TV HD': logobase + 'DoGC3WJCbY8YaqqDRNKozHipJbcv4w.png',
    u'Silk Sport 1': logobase + 'l9Kgggrn91YSci1WRNQRrYnziLsrk1.png',
    u'Silk Sport 2': logobase + '2NPZkLzR4bl5J41EYH9Ytj5BrscRwG.png',
    u'Silk Sport 3': logobase + 'i5EprR0AeYz8KlWNmYlBuAwSDBmRBE.png',
    u'SinoVision': logobase + 'W1IlMtsnfmHvQArfHnAVyLY9sX5ThN.png',
    u'Sixx Deutschland': logobase + 'emrddE60uxhIjLTXqefXNX3kPhoPKo.png',
    u'Sjuan': logobase + 'OjB0gFaycsTFNFz0CcavuvCh513Fx4.png',
    u'Sky News Arabia': logobase + 'acfs0ddLGN3FZuzjd3zjOn3uA9aKKo.png',
    u'Sky News HD': logobase + 'GupjQTKRNFRjH3ivdaHMuae46yeYtK.png',
    u'Sky Sport News HD Deutschland': logobase + 'uupT7acfhgUb7EfydyHvj5oKeDaAco.png',
    u'SKY TG24 (IT)': logobase + 'gjvJXU0oimEfkXGYqxCLqEtfEGY7Ku.png',
    u'Sky Turk 360': logobase + 'P0aX2Dgvo6w45R7nDxGeKRdqENQbxn.png',
    u'Slagr TV': logobase + 'ChhzBYin80EukVyumdt650ekaWn6GT.png',
    u'Sonnenklar TV HD': logobase + 'BrbI4D2OypLQpGgZ9VCYzteQ4BMJYX.png',
    u'Sonus FM TV': logobase + 'eljJtM97sGaAjial9DnnXuigSqhrmG.png',
    u'Sony Channel Turkey': logobase + 'pqoXLibor4qsqqovbZdMMmrZpQbJu6.png',
    u'Sony Sci-Fi': logobase + 'zLWEgf9BbxBr1TR2Qj2NxVQBuPecEP.png',
    u'Sony Turbo': logobase + 'CaPjVaQrpyN138TarQ7CYBqBOz0ZF7.png',
    u'SOS Kanal': logobase + 'kalI2gHhuVjTbUvoIxhNyNG8xywdBA.png',
    u'Space TV': logobase + '5WT7hzZe3qEzKV1Diqwyd37xS671BG.png',
    u'Sparhandy TV': logobase + 'mIu8nokHbOarWz1WHdGzUKOMABteJf.png',
    u'Spike': logobase + 'KPNj0b4rZBtEB50yasdM72Th7UqrKm.png',
    u'Spirit TV': logobase + 'hxf4C62ltB36O5jGtygHeAhNK52BFA.png',
    u'Sport Klub Polska HD': logobase + 'ctQJarsbeQz6SDOIJIXkcHUfyx0M4K.png',
    u'Sportal TV': logobase + 'EldIOBOP1val4pcUHK0Pqtu6vzEgXW.png',
    u'Standby TV': logobase + '9P2ErrVIWeOdYThxO66FRVpUAC29gp.png',
    u'Star Cinema HD': logobase + 'yEjNYR7r6uXvU4i5b71lBQg7Icj19B.png',
    u'Stars TV': logobase + 'fJSB955jGfuiujIhgwidmFjLyTtfro.png',
    u'Stingray iConcerts Europe HD': logobase + 'fHqCqzC7nx95ZO3ixdyBIW0zoWvCKL.png',
    u'Stopklatka TV': logobase + 'iFmzjinGdnBrtv3DV9X1j7gFHToAwI.png',
    u'STREEK TV': logobase + 'Tjmt7vjp2xTwX3rjqBeKrabMaK5f2S.png',
    u'Studio 100 TV': logobase + 'raQkGMpr96BCqdNRDnquqh8U2WUYkB.png',
    u'STV (Одесса)': logobase + 'zUGaJKfij0jzxPhi5dmgX9ruU38Gj1.png',
    u'Super Polsat HD': logobase + 'GVn2SZIpGu6UTgEXw8cNwaeyEu9eJM.png',
    u'Super RTL Austria': logobase + '4qleVBuVQZLqS9T0Q48wuadVBohjCc.png',
    u'Super RTL Deutschland': logobase + 'ZuWknHNdM5WoPLlz1UwOzAp3fNGh3L.png',
    u'Super Tennis HD': logobase + 'mjQW91VJdjIEhADvOO2s6OiKNeUdUK.png',
    u'SWR Dasding': logobase + 'LAqpx138172Y0Il1jRI069BnLrMtde.png',
    u'Tallinna TV': logobase + 'o4NWk7Uy2y8El55tqHcjXcVhxZajzH.png',
    u'TBN Armenia': logobase + 'FSrN4uAw8CuqZxbdyQptWUcnYfzTPr.png',
    u'TBN Europe': logobase + 'PYnC32imVreBhjjl4G70Kx1dpwKeLa.png',
    u'TBN Украина HD': logobase + 'nbbxlbN1EN8hTjoRyRzWV4tJDDht3g.png',
    u'TBS News (Japan)': logobase + 'OdHDN9mZiX5Vzpf86xkjnnVqvSRWCb.png',
    u'Tele 5': logobase + 'BahbW0uBxpVOHayoLrr6uFcaBsiYSc.png',
    u'Tele Arena HD (Италия)': logobase + 'NXPracJAldyYcigtPLJwqQLFMjUxyP.png',
    u'Tele Diogene (Италия)': logobase + '7RkADeN18pXqR3Lfgiqb4c7oazmek6.png',
    u'TeleBasel (Германия)': logobase + 'I1nHYxn5rgR8w54OD7bDoIheKvTMay.png',
    u'Teleceiba Canal 7': logobase + 'FWfNNLeoA2RyznBSX0odwCj670nPoj.png',
    u'Telemar (Spain)': logobase + 'rNdkNeiAHS2fRijdqSXFVZSyGrjYzy.png',
    u'TeleMia': logobase + 'RrEd1b716C4Q0zPCXykQJRk4w5Es38.png',
    u'TeleMoldova (Moldova)': logobase + 't8gQs1ufiqZT9NoYrVqALuBbWzIWHf.png',
    u'Teleonda': logobase + 'CTzjSdaDyLWrh6ZFq5ozNPMndwtnAt.png',
    u'TelePace HD': logobase + 'RbeGZFeXIAMMmF20RboljsULjRqGM7.png',
    u'TelePavia': logobase + 'LYUkjk9UP7DXD7hEVhFcItqawuiRVI.png',
    u'Teleromagna': logobase + 'ntcVrySNgKlJW3u5IMzPJUpEuBtflK.png',
    u'Teleromagna 24': logobase + 'RLtwO0NtLFEEZSuPuThhpfcOBhSJyb.png',
    u'Teleromagna Mia': logobase + 'r7bX2vC0SoSJdwSVchuZXTgJrXsgTK.png',
    u'TeleSafor': logobase + 'KVGpMvzllgRRsXaSPRyJQPCdPgjXkE.png',
    u'Telesur': logobase + 'siuoxgaNlUS4dWdLBpiRBwdg8pRntj.png',
    u'Texas Student TV': logobase + '8OvhAGXAWbzqeI2OP3v7PGCHX0Q9Yh.png',
    u'Tg Norba24': logobase + 'YOKOm1EAlSnOQ8iIDFk4sIpqtFqCgr.png',
    u'The Country Network': logobase + '5E12MHD6VZCKuecPei5t3jvbZifbUp.png',
    u'The Dove (USA)': logobase + 'OY78drRvGpmG0c5FWuEdHp28IX4MTM.png',
    u'The Jewellery Channel': logobase + 'xTdjjMgsQVowngrH9344tz1oY2qzZH.png',
    u'The Word Network': logobase + 'R9UwwsopX0YntvnH7OmrENwZrKhuIn.png',
    u'This is Bulgaria HD': logobase + 'HnJUspxZDwrGeNgBlwdnCv47HW5azX.png',
    u'TiJi': logobase + 'mD3GW0E7rdPwc4stjk7xrLI2gZn4Hq.png',
    u'Tirol TV': logobase + '0acLGbY8FPKneK2XWmb690Gjd1vAHZ.png',
    u'TJK TV': logobase + 'Sd087yjCcQiiQLbcvdKBtNt724TdWB.png',
    u'TLC': logobase + 'gT4olUY9nFJbGRCdwd7hHJp1NJ5eJr.png',
    u'TLC Deutschland': logobase + 'qyRXKO7N6zIls64vyyAMybjEqGj8xc.png',
    u'TLC HD': logobase + 'gT4olUY9nFJbGRCdwd7hHJp1NJ5eJr.png',
    u'TLC HD (Polska)': logobase + 'P1xEBvSoMdwlW8me2wdUYtUw0y27Uo.png',
    u'Toggo Plus': logobase + 'sW9BExJpOvrzPy0nT7N2KO22XhBK6r.png',
    u'Top Latino TV': logobase + 'BDXka9h82ublVtMVyvzitYLUtHv261.png',
    u'Top Shop': logobase + 'uD257Lhw7Ko2YD1reC0nRqW7lpy93D.png',
    u'TOP Sound': logobase + 'omm70R24nvY86MlQs08QL4XctaPmEF.png',
    u'torrent-tv.ru': logobase + '3LPFwCA0df8lBebrPhStZVoNWLMjvk.png',
    u'Travel + adventure': logobase + 'b1HifWKMyefmDDvaDAJTwNNTaD8LF4.png',
    u'Travel + adventure HD': logobase + 'b1HifWKMyefmDDvaDAJTwNNTaD8LF4.png',
    u'Travel Channel': logobase + 'fhmrYjlpC0YMxFd2RqOolbjlXMr0tI.png',
    u'Travel Channel HD': logobase + 'zfnAGLCvIu1fx9hfrITAZMoo9HYww4.png',
    u'Trick': logobase + 'je4tkRt1VeVriaLLup9ecbh8kKeBAW.png',
    u'TRT 1': logobase + 'QrefawvYSDUArM9SyL4wh7L7VpYD1o.png',
    u'TRT COCUK': logobase + 'fTnANkAi44PkPGHW9DCKVbddzNzqwR.png',
    u'TRT KURDI': logobase + 'u61OPwqStFXZqcIUskE3Vo7Afqnjnl.png',
    u'TRT SPOR': logobase + 'S59caVegNwZy9m05oBiRfU5FPmPtZ2.png',
    u'TRT Turk': logobase + 'BDkqm302OLdoXCwpKFVUe8S43OlWj9.png',
    u'TRT WORLD HD': logobase + 'TKAqY2tQhsn7H8RJDwVsuJ6aZAsu69.png',
    u'Tuff TV': logobase + 'jHIkqIpwnGhzAEQGrEvNgYvNiJM6gU.png',
    u'TV 1000': logobase + 'WJMEvVafVakrm7BUMy1lzku7VQCx25.png',
    u'TV 1000 Action East': logobase + 'GblbxkDGXZyW5oWt9W8wuERQAiZ7ZT.png',
    u'TV 1000 World Kino': logobase + 'CQfnaO6lQvA178UDr2HfQjZVvFdgJc.png',
    u'TV 1000 Русское кино': logobase + 'ch5DX6f8hxDnmyzrjotUoKHNGzcw9P.png',
    u'TV 2': logobase + 'pbu2RfCMXAnQKrfBnobGLmUft4T6kL.png',
    u'TV 4': logobase + 'c9bfBbAkwQ5rjCo3PZQVASQprrgTOR.png',
    u'TV 4 HD (Polska)': logobase + 'ERRr4n9SORrKBtqft7pSaUsPLWQcCh.png',
    u'TV Biznes': logobase + 'X00YTwcoRLp0cxrdG0ctfZfjYPvYnp.png',
    u'TV CITY (Азербайджан)': logobase + 'A4ZXzoMGK4bGs2KQn0WqlAjt4n99jt.png',
    u'TV Cromtel HD': logobase + 'fMMxa3XtjweBv7OrEJAE2N6wPg45WW.png',
    u'TV Evropa Bulgaria': logobase + '78SVTKvw7RzoIMaDyfjdH6tqRtGwF3.png',
    u'TV Galicia Espana': logobase + 'SRsZdDiaCqnJOrMISvMbKDWpreKrah.png',
    u'TV Halle HD (Германия)': logobase + '7lZJVsnUiAcaIoAKjOFl1Uo9eh65sb.png',
    u'TV Inforbahia': logobase + 'WqNcaaWDWlaHjMwUi9eurYyCVav643.png',
    u'TV J SID': logobase + 'I7XYVZ8oQ4Lmwvkbne2ffxaRk8v2zZ.png',
    u'TV Kujawy (PL)': logobase + 'Y6hkqlKrrcYqC4t8qncKkQOYOCFiW6.png',
    u'TV Mackenzie': logobase + 't8nwqLdKupIRwVyRb9tE7ZBYOfToyA.png',
    u'TV Mall': logobase + 'hao8n2RWJzxwNaiVHUawwkNVG6X4Zp.png',
    u'TV MANA (RUS)': logobase + 'ue6tILTqNlxZVouGCejRAfDHpdQIem.png',
    u'TV Peru (Перу)': logobase + 'Tp7ElkeQ3gkL3F7PkQqkDSw22lE82v.png',
    u'TV XXI (TV21)': logobase + 'TKchoTWZFRMmGDBok08zoEFJ8mJJCe.png',
    u'TV+ BG': logobase + '2fgZTgXpAgZG0EQOkZD6x5dCEtdbVh.png',
    u'TV-4 (Украина)': logobase + 'aAcZbGFfyqMbiTybIo3eDV2gty3zFy.png',
    u'TV-5': logobase + 'iPHeoajUJttv5qZl2yfcOYB1qFx6nv.png',
    u'TV2000 (Italy)': logobase + 'Zmxv2IMaKkXe7u6UET5oK2IuqKKImf.png',
    u'TV3 (Estonia)': logobase + 'IdcgDRXYPBO8ZguuCAvFnN6z3vCzuX.png',
    u'TV3 Catalunya': logobase + 'JdogLgSiKoXxC7ZlxVLogeOLMQUQyN.png',
    u'TV4 Film': logobase + 'i9tPWyxkVpAWtTPUBFrl7Na5vJDq11.png',
    u'TV5 Monde': logobase + 'ko7rbRBnyK1iINkLOA2adRvgVOEgUK.png',
    u'TV6': logobase + 'l1UpPzlU6nnHGIAdtNGTgns5V2l6jV.png',
    u'TV6 (Latvia)': logobase + 'Tq1sAzuOe5um8SHPbFkGNF32PiWUXO.png',
    u'TV7 (RU)': logobase + 'BEhtrXmaNqKY4rUYCOPGoRsRQFThK1.png',
    u'TVA HD (Германия)': logobase + 'edhuk2NgSxGCU93hCBlLj6NGirEn7j.png',
    u'TVl': logobase + 'h1e738AaaIYkeDvRWlbYIZSBsMwAyN.png',
    u'TVM Channel': logobase + 'JQEVM8T7WFUHKANNFberjZHBCevvNo.png',
    u'TVM3': logobase + 'IZsjSlfB1quB9NtJFHhx2unVgdly5W.png',
    u'TVP Kultura': logobase + 'SpwsfxtpHruDbdnc4Yl9fzQUKIAN4o.png',
    u'TVP Rozrywka': logobase + '3C1R2FT6ZYuAiF59BhQH5v2porPBMu.png',
    u'TVP Seriale': logobase + 'xdk6VGw20t61EXwWML3dFZiLNIuBdE.png',
    u'TVP Sport HD': logobase + 'IjAMy6zslU2EpMXd2n1UiHfysLlwCg.png',
    u'TVPI France': logobase + 'R7jr9iIXzmHeezzwV8Di4KjxD5I6XF.png',
    u'TVSN': logobase + 'BICZgtp5SKCXatYW9P8tLYnAqtk9YP.png',
    u'U TV': logobase + 'Qa3nKOGYfqjSUVg6GBN7GjwVokNI8T.png',
    u'UA:Крим': logobase + '1oa1CrfXZ94gpdjszpFhOmEtO8mV6K.png',
    u'UA:Культура': logobase + 'pyKdve4YhoChQFGSha8J0FBWBf302a.png',
    u'UATV': logobase + '83AcB7NfDhEh4tEcJx7d5Lm1l6dzpB.png',
    u'UNIVER TV HD (Казань)': logobase + 'ONPJ3bHxjPtUb0FKBOmNYuGArxCxKF.png',
    u'Universal Channel HD (Polska)': logobase + 'tuXQTsJk06B40kHN3LA0MkY1sbPhHR.png',
    u'VH1': logobase + '58.png',
    u'VH1 Classic': logobase + 'FhxUFQ2Bsfom4vb8Ce41gFObAbh1Vh.png',
    u'Viasat Explore': logobase + 'uCqpsdKP0ialUUYxUk2fXshYdYfxzW.png',
    u'Viasat Golf': logobase + 'IGpQl5iTxaDEPyKffdDEpU0EU0SPiO.png',
    u'Viasat History': logobase + 'MWGbB8wJp5Gm4vbPHl0ktohDDjMKdr.png',
    u'Viasat Motor': logobase + 'ZyrdjMba1qEqZZVHDSQq9ZQrgx3sjP.png',
    u'Viasat Nature East': logobase + 'yimDcPvajJcUKQm9bY15cDdp3rJFcp.png',
    u'Viasat Nature-History HD': logobase + 'pSP6zxmuO4PU6xa6KRlZ9L8vvVM2Dy.png',
    u'Viasat Sport': logobase + 'prAZKkny3W1HGM03lP0EhzcMmTPZdi.png',
    u'Viasat Sport Baltic': logobase + 'ZIITckvF1w5u1MlubmhoG45HxPgcZZ.png',
    u'Viasat Sport HD': logobase + 'prAZKkny3W1HGM03lP0EhzcMmTPZdi.png',
    u'Vibee TV HD': logobase + 'RVzyz7XAFWLJNhpgq9lJpa6RtB7OVc.png',
    u'Video Star TV': logobase + 'yv1DY0s8OqG9msRGm1dJFA1vDswXkQ.png',
    u'ViP Comedy': logobase + 'lO9PoF8cTaTlehJPMkkOqZM1cYEPcc.png',
    u'ViP Megahit': logobase + 'mPzm416HTmW7uEPgjICGeKK95Tma5Y.png',
    u'ViP Premiere': logobase + 'NxpfVz8kXfNmwuj0cIhIQewuII9j7m.png',
    u'Virgin Radio TV': logobase + '6DgkEMl3HtkpKQbzVovPdSYhy9f3ne.png',
    u'Visit-X HD': logobase + 'PKLqXFmYlYpo1RbkynS7SfL79gH9fg.png',
    u'Viva Austria': logobase + 'sUPeS0888UCOztGNrzvtpXumWwg3ao.png',
    u'VoA TV': logobase + 'PolTZwuevxqMoAIq1ngchK04tmZr5S.png',
    u'VoA TV Persian': logobase + '5unfKoJm26gCTZ4SGwa38KnwvDHRAw.png',
    u'VOX Austria': logobase + 'XxN11Gid41Fq8TlK4SYDwqoI568qhZ.png',
    u'VOX Deutschland': logobase + 'tfHvZ5lu767ghoYW71SJ3UoYd0AZes.png',
    u'VOX Regional': logobase + 'cMgt4ea4ygoCixAX2dCcVgWmwnjAOX.png',
    u'VOX Switzerland': logobase + 'zktxNDxdpLzHC1ZVHOhtkg1jX9aIKW.png',
    u'VTK Bulgaria': logobase + 'L8wHk1KojYnXLSq9go9ihuCr1LM4kt.png',
    u'W24': logobase + 'c6n6W2R74pC4XxdBuMd2w4HuPNB8pl.png',
    u'WAU HD': logobase + 'VOnvAd75wacX1AadU37GexMftJzQWv.png',
    u'WBC': logobase + '7XAr6WORzneXQ3c0hoijptt3anju3x.png',
    u'Welt der Wunder': logobase + 'VNsOpaG7oXH4JiSscDRHbHFP3bPu36.png',
    u'WFGC TV': logobase + 'f6umSzmvgiWzq4qj6tmdE1hy4YO7dZ.png',
    u'World Fashion': logobase + '2YI4sT9YkGezrw9vZPn0uIRhZ7E2BV.png',
    u'World Fashion Channel HD (Россия)': logobase + '2SSUxaYn3Oow29OOSVdzNoPFGch1SI.png',
    u'WOW TV EL SALVADOR': logobase + 'Qu5LpKZhZ6liUbeNRTboQA5rcuPC1r.png',
    u'Xezer TV': logobase + '1i5OaA3fQiek2oK99SneRSm0vwTCkW.png',
    u'XITE HD (NL)': logobase + 'N1zheznjGW9sV4i8GChlBD6sJ3009k.png',
    u'XITE Music  HD (GR)': logobase + 'FeWCTdXHZKnid3qXQNH7afhkBDdA0t.png',
    u'XSPORT UA HD': logobase + 'WwZ8GH1nhDLqgTuB1YWIe3gJJvVirK.png',
    u'Yle 1': logobase + 'D09iFm6lgnlTJ44WcN4ZROl2pC0TW9.png',
    u'ZDF': logobase + '5SH5FeZiITw27CPxscjksZp272u7He.png',
    u'ZDFinfo': logobase + 'pYRaR723RgoEOfYqkQUcFin7hzBfk6.png',
    u'ZDFNeo': logobase + 'IzZ1Jky9uy3oIVlXb7MEHtgMrArFWq.png',
    u'Zee TV': logobase + '1HooaeEhMSvpKmWv6nneZxnTmG5r6Q.png',
    u'Zest TV': logobase + 'mcF7ChQAr2KdlJ6zlnPLOL7VF3u4IB.png',
    u'Zeta TV': logobase + 'oq14JrtW5WdHXJYbjOctzFkefAYc9R.png',
    u'ZIK (Украина)': logobase + 'dB1PmpYtgeI0C4u7Cv1QoXHlvc4JtT.png',
    u'Zoom': logobase + 'SyisYhg411o7z9kXci4vfpLq4KBZZ4.png',
    u'Zoom TV': logobase + 'nS7cFyCvFWhTirQEqU0ubhlfRoDEvo.png',
    u'Zougla TV': logobase + 'HNauJ5nu1ROWERy0K4wT2EvrwOPm8a.png',
    u'ZTV': logobase + 'gg4M1pWkBcsnGgAiEB4gl5hIjoQDXD.png',
    u'А1 (Одесса)': logobase + 'WVrkBV2cobz7t9e8FvN6PJTZjnSjRP.png',
    u'Абаза ТВ': logobase + '7Dy3BHMZB5ZACk4BRKVPiPF54QfLwu.png',
    u'Авто 24': logobase + 'GZwKgvkC0vfYquFAn1dKhppNxdDit9.png',
    u'Авто плюс': logobase + 'WkRxjy6fJEBJ5NZiaGn2j05eqfFfQq.png',
    u'Аист': logobase + 'V8vU7Svp3W6cDwcGAGc4QlehsDFxsl.png',
    u'Анекдот ТВ': logobase + '8Ju785o93wbKtVP7Tk80wQjGaL8hhV.png',
    u'Ариг Ус 24': logobase + 'kLnnsZsvaZd9ijlxh9mMhzltJSJJN3.png',
    u'АрктикТВ': logobase + 'cwkVCO8OkPO5wNPC9bmVtpuF6iol2b.png',
    u'Архыз24': logobase + 'tuMbRlnkeMiYQ6u9oeiAVfHF0F20RB.png',
    u'Астрахань 24': logobase + 'FeMgg2g4NLpCyQsSsW61fiTKNhHr47.png',
    u'Астрахань 24 HD': logobase + 'uY5oOpKeVKrOryxdeMtuPwaiAj1Xz1.png',
    u'Атамекен (Казахстан)': logobase + '91qNsUznTT6Qs7Badomq4dFeUw0kFL.png',
    u'АТВ Ставрополь': logobase + 'N3CfiozXcw5Kvqwgztz94IXv0W4OEd.png',
    u'Афонтово': logobase + 'XzZ47QdIa6au6seekqdxqk8kUFOGjt.png',
    u'Баланс ТВ HD': logobase + 'pa4hYXeADK6zrianNiMNRtioXPffSw.png',
    u'Барс': logobase + 'PWZbjRJvtr4K2b9LuIdsTTWi1CHP8q.png',
    u'Беларусь 1': logobase + 'S32pk5GPcXbTyyCllIjfpqPPkBAy4Q.png',
    u'Беларусь 2': logobase + 'PsdtPguSJF4nNewH5pHF6eRMahFNkz.png',
    u'Беларусь 24': logobase + 'GxA1KJP5YwpWc38BoPEmLwQH6uDeEz.png',
    u'Беларусь 3': logobase + 'Igl227Na6U9sHF79uhY8T2Oc80azfV.png',
    u'Беларусь 4 Могилёв': logobase + 'WGJwxWMD9TKs9v0GsPIyUWZka9QIx0.png',
    u'Беларусь 5': logobase + 'WNJiWQKtAo56IPbe0OLFPoNMNb10Az.png',
    u'БелБизнесЧенел': logobase + 'k6Nh9OCsvPPx4ozKkWxrVoZ9ZQiyJ6.png',
    u'Белгород 24': logobase + 'aqZSStASur6jhbrIKJVYBxCiesXnIl.png',
    u'БелМуз ТВ': logobase + '4ApGCRqp0ZEoRNGZ5FSQZJxNcXKape.png',
    u'БелРос': logobase + 'IcisoCbKJuQgDDD1OFhEbbAKQCSa8Y.png',
    u'Бигуди': logobase + 'JvcMdB5e6KVBpbXT12ulzmDqenheRx.png',
    u'БИМ ТВ': logobase + 'RiEMCZ0GOrdmH18puNKMsMnvUijbrL.png',
    u'БиТиВи  (B TV)  BULGARIA': logobase + 'u6oQBDESxHiCuNgMfDfuQw4UhoVBF0.png',
    u'Бобер': logobase + '2Edln8vEbg7UUSVUo7lIJPR780OWAR.png',
    u'Бокс ТВ': logobase + 's3qlrVrIjISf7K0G4HHRYw5rmAej4b.png',
    u'Бокс ТВ HD': logobase + 'GOUrw8oAZvvAksR8BfJWTqUUJ6DLt0.png',
    u'Большая Азия': logobase + 'hULNn5zbfFwXa9EWNXprvJYeDTCbwB.png',
    u'Большая Азия HD': logobase + '52I2UFCkK36M1rEIIbS2rPe7QTolhU.png',
    u'БРТ': logobase + 'bGM0ZSO2B3UfFml78yPJ0OykAAQRrd.png',
    u'Брянская губерния': logobase + 'V5M08NU3jRbd2wKvtVLIRbg9J6ObAZ.png',
    u'БСТ': logobase + '05dZ8fzOmf1lXYue2OvVsQ21eIeX69.png',
    u'БУМ ТВ HD': logobase + 'wHMGSLfPCHU2MX1y1ro6ZqQMxe0pcE.png',
    u'В гостях у сказки': logobase + 'J0k1mbEoFNnvnNvOpTP0i8aLObGJM8.png',
    u'В мире животных HD': logobase + 'NefS7NwexRum5zxjT2EFFBgy7pEp7T.png',
    u'ВИКОМ': logobase + '8TudZ488TLzkk2rJehda4BYYgrSgMg.png',
    u'Винтаж ТВ': logobase + '6yngbEKfgy6XtMw28INQCoOdulf2tC.png',
    u'Витрина ТВ': logobase + '08OQh8bZ7WMdHJSWbQkgF5icrIH9Dq.png',
    u'Вместе РФ': logobase + 'qa50GYekwBWym7KtoJdzrWHWqN8TeU.png',
    u'Вместе РФ HD': logobase + 'JxgnwFeOwqX02WHKKdkWJDoAtpWTCT.png',
    u'Возрождение ТВ': logobase + 'CKWaxJsLQYiJmnkLhtysIn8hb0NK8b.png',
    u'Волга ТВ': logobase + '1CZtoSAY9ZjEavNeGFTrPvSvFxjAHH.png',
    u'Волгоград 24': logobase + 'iCZ3kRKXWJITuH34sJ3HPRNedTtk4f.png',
    u'Волжский +': logobase + 'KTjzB2p43WzPBp2KxAW6VjBL5MUz64.png',
    u'Вопросы и Oтветы': logobase + 'VkkEcZ1m9h8HRcQyF9azGHv1ZMGIBl.png',
    u'Время': logobase + 'F44yKDJQLsX0llpZ2wupg8V5vHx5fF.png',
    u'ВРТ Электросталь': logobase + 'hTWcIumzWRmfpuwcli0j15G4ZLhYih.png',
    u'Вся Уфа': logobase + 'grdMBeR1FvL4fqlYFy4l28jxEHVg4S.png',
    u'ВТВ': logobase + 'ZModP65rWODi3dlXs9iaxJiXJCpma6.png',
    u'Галичина': logobase + '77frl2Ae8YNhaTSw2380BMVLF0em89.png',
    u'Глас': logobase + '6m1xUI7vFyadFMFxXeIZjlATt7rlWw.png',
    u'Говорит Москва': logobase + 'aWMjBtR9OQ6Q3DmOOSFAWQgePEdrYX.png',
    u'Горизонт': logobase + 'f6wqkzO4WZW7D5Z9xIB4VkMRGmgXUU.png',
    u'Горная страна': logobase + '5bzGO0M7OgMhzgOfWi75c6btrYj28z.png',
    u'Громадське': logobase + 'tHAyXEoFX2NzCPgAAsbymwTsL6eEEj.png',
    u'Губерния (Самара)': logobase + 'm6uotRQ8g6fjMLfVchecqsj0cbCITM.png',
    u'Губерния ТВ (Воронеж)': logobase + '41RRCOUuWTPYLZ23EwpwI7yJXNNwIx.png',
    u'Дайвинг ТВ': logobase + 'MDNQgEh4n6dq9NT8RMaoY0eo2yDTMQ.png',
    u'Дача': logobase + 'mX1irJVUyLtrXr9vfDdhknRqiqV9wA.png',
    u'Детектив ТВ': logobase + 'Xp6oaxT0R8irwKqsjJi6I4ZiyRabeC.png',
    u'Детский': logobase + 'jk8kody2p38CKdj5KGXWMwRLjgFIlG.png',
    u'Детский мир': logobase + '00Vf3rPABNnbNQ6Rv0dnfcg3JsJelA.png',
    u'Диалоги о рыбалке': logobase + 'GClhagREnoOffF19KRQFaepMQMXmfO.png',
    u'Дикий ТВ': logobase + 'mGXCAjsZvDFoYNIeCpcNS36QUJ2Kv9.png',
    u'Дисконт ТВ': logobase + 'XxxVSXJRbIMm80LZd6RmHs4Wn8hFPJ.png',
    u'Дождь': logobase + '381.png',
    u'Дождь HD': logobase + 'zjm0eump1MWxCs5HCsNhO5AITiWcE7.png',
    u'Доктор': logobase + 'FznqTpJ71LS3RLESzMOHhNDxJMwBE8.png',
    u'Дом кино': logobase + 'jlC78Fy13KWjQUN6l3FtbsRLZDvc0x.png',
    u'Дом кино Премиум HD': logobase + 'Xg5l3gO5SnER0pwHhgsbHVMqSb42ty.png',
    u'Домашние животные': logobase + 'HiWAmn5RvUKNJnSW2Jhxjs6maoNFV7.png',
    u'Домашний': logobase + 'qmqrH2E2EX11qitbIvq0CYsxQjsHGm.png',
    u'Домашний (+2)': logobase + 'PjE0Qj806BqBC0IOuZbc9BhFaLdxlU.png',
    u'Домашний International': logobase + 'JuScBRkcnTOsuCxUOcXqgW13l5d03d.png',
    u'Домашний магазин': logobase + 'yhzajV7vdLogQzMKat0rLJWaDkPpTP.png',
    u'Дон 24': logobase + 'qB34tCfiy8RoCwBprbt3yBlb9QTb7i.png',
    u'Донбас': logobase + 'vsj1IA3Z8QVL3AzzuN4EshgT4LUmRr.png',
    u'Дорама': logobase + 'Bxfzn1hUaZ9EcSoOar0JZPrRL1vNnX.png',
    u'Драйв ТВ': logobase + 'IzUNez8spn44tivGiApqajydfeOwxg.png',
    u'Думская TV HD (Одесса)': logobase + 'G0FTTkLLodhoSHHXCUbarxdg8Dsgfp.png',
    u'Евпатория ТВ': logobase + 'tYGpbjPNcUALayGsAKCvQQofS3mkxG.png',
    u'Еврокино': logobase + '34mszCG0j0Vf6kFcMrLPnFEA8UPdu6.png',
    u'Евроновости': logobase + '6HRWXfDaZ5zdwbwOsq383OrtV4MprK.png',
    u'ЕГЭ ТВ': logobase + 'dwe86aR0KHW2VzEyj863SViH9wtUGL.png',
    u'Еда HD': logobase + 'ojUD1jhpv7HBOLmubpEBOsANkpYNtk.png',
    u'Еда ТВ': logobase + 'BEpOeiR2iGtmqLOTiVM9HeUKgEUxb0.png',
    u'Ел арна (KZ)': logobase + 'CEzpzKtd3rR5ogcCnWkWzK6dUDntkO.png',
    u'Енисей': logobase + 'BwSuUNSjziZ2cfyyOu6DGwTkT8AkAX.png',
    u'Ералаш HD': logobase + 'kN5BJ9wll0h7fQI5hmu9i7fnNz88hG.png',
    u'Еспресо ТВ': logobase + 'lOwm890F5URuR5Ej7IacerzECPIDt4.png',
    u'Жара': logobase + 'DbKEKL5gUOFHiruYRjY2H9gTLOV5mu.png',
    u'Живая Планета': logobase + 'xgKSMwqBdEyXnbVgb8LtNXSMiaPcOx.png',
    u'Живая природа HD': logobase + 'L9qmq6UIprbg4VBQA46tqRjQ22thsp.png',
    u'Живи': logobase + 'cOluSjslxxs3JZtSVO8c15xh7h8SDU.png',
    u'Житомир': logobase + '3QERPthuUXZKOAuut0MC1dsEjLXPxe.png',
    u'Загорoдный HD': logobase + 's3USV2NVMzAvO3W6evojTiVLXFugul.png',
    u'Загородная жизнь': logobase + 'cGGo8HRkVhy66UXKXZ4tH5HyUaaxJA.png',
    u'Загородный': logobase + 'RX345W0BBqJbR3XdROHMi4dnbwqwlt.png',
    u'Звезда': logobase + '0HLRrFHt2QIkbJpLc1fy0RVe7hqCEC.png',
    u'Звезда (+2)': logobase + 'qLINlvhHbkcRY4UjDpf4sqPzbSJcYO.png',
    u'Звезда (+4)': logobase + 'OuOzOS8YQYpfvSiALYw8RE79MLLW8a.png',
    u'Здоровое ТВ': logobase + 'kS1cWLwe2CezP2SDrKODooTeYRcsqF.png',
    u'Зоо ТВ': logobase + 'RtAhntWPlKQs6CIYAb72piNF9EsN3E.png',
    u'Зоопарк': logobase + '1Ugpb5T1THFcFpn19Mnua21KxHkjct.png',
    u'Известия': logobase + '8kCEfoFFrcYOp9XirSSHgjVdEIU9Qr.png',
    u'Известия HD': logobase + 'oDcPw8gfynentKu5CDXKlA0lo86tdK.png',
    u'ИКС': logobase + 'ty9vXw4HihxvSkY1lLdLocVCms3KRN.png',
    u'Иллюзион+': logobase + '8LToTNvWRBHvb5IKoteKm8EwAGw8mv.png',
    u'Ингушетия 24': logobase + 'EkF7CR2dTqpBPz9JlGNRxc8NATTcus.png',
    u'Индиго': logobase + 'dFIp5shmC5DbfWIDVaFh7coAofmLON.png',
    u'Индийское кино': logobase + 'y8wvb5nc77vn5c4x8kinv85c7mv6n875c84.png',
    u'Интер': logobase + '3SP67FapzyZqMVZTPiJIcN09KRkTeu.png',
    u'История': logobase + 'PNRaeOUFzOPFtrclFBBRTckj6Lvo0u.png',
    u'К1': logobase + 'mk2mYb28HFIxkFIiMNQWmKUdn1Y8hD.png',
    u'К2': logobase + 'IjG76jf8k8HTNLooNpUiEXtkPfA2rG.png',
    u'Калейдоскоп ТВ': logobase + 'YJMqmzlZ87QeXYm9XpjH0XzpjljNcU.png',
    u'Камеры Санкт-Петербурга': logobase + 'jHbY0LrB7JKBBWzWC1ctPD6uDqQNnx.png',
    u'Канал 3 Болгария': logobase + '9IFz2CQBSYPJW0ShpmyTBP5VZicaIA.png',
    u'Караван ТВ': logobase + 'mHy9hfnjiBLKffHjrNenIvHCyzfjvf.png',
    u'Карапуз ТВ HD': logobase + 'OAjEar9vMUkx4jaWrJ3Ti2MIFUQioK.png',
    u'Карусель': logobase + 'S233D4b6eq7KOXfdyi4dY2GokKeltg.png',
    u'Карусель (+3)': logobase + 'cYXQq7FnkEBAyYxfoPPsL2y3fwMDKU.png',
    u'Карусель (+7)': logobase + 'W1eVRirHM60k3LEiHPV5ZlWL5WOA1K.png',
    u'Карусель International': logobase + 'S233D4b6eq7KOXfdyi4dY2GokKeltg.png',
    u'Катунь 24': logobase + 'sfoJYJn4BTNSGxDV3NSytnzzPgevVn.png',
    u'КВН ТВ': logobase + 'uHs398usENAAKycx5NFCHiC0jDtzrc.png',
    u'Киевская Русь': logobase + 'C1AZimW2NnNA17H1uJLxxePUMTPQZ7.png',
    u'Кино ТВ': logobase + 'KkITMDICqC1erWdSqyOqoccqde2wHC.png',
    u'Кино ТВ HD': logobase + 'NGQLEmlltpslVNKkD0htUF7CogGXqX.png',
    u'Кинокомедия': logobase + 'y087hci8ityixcnyxinxoafhiu.png',
    u'Киноменю HD': logobase + 'jI8oqP5EBmcasurdGXR0eXQZRuar3L.png',
    u'Киномикс': logobase + 'y6b876ih8g7R876hfug3897wrhj.png',
    u'Кинопоказ': logobase + 'L2qsABeMEDKOSG4Tvh7XpfvX2BfksG.png',
    u'Кинопоказ 1 HD': logobase + 'pNA1vR3sPoovYNKzO4TU6NQcSXNqjk.png',
    u'Кинопоказ 2 HD': logobase + 'Yf2XKrtorOF2wSZ23Q9NHhL2MfOcqi.png',
    u'КиноПремиум HD': logobase + 'p580CRZ8bBS6dw3plMWhhxXSzQ59uS.png',
    u'Кинопремьера HD': logobase + 'y4Ihg8o7ikgJHF768iJHFH76iu.png',
    u'Киносвидание': logobase + 'y1876iuyf7645urjg56utfy.png',
    u'Киносемья': logobase + 'y2oerfuhdj2108nbs4ev875esk47dn.png',
    u'Киносерия': logobase + 'o07C0d3hHzAtT4in0l3E4U1I6rQoTY.png',
    u'Кинохит': logobase + 'y3igbjZ&LGyqDWGIASUY78AWID.png',
    u'Классика кино': logobase + 'JUnIt4flcwcD3Gu3qInuPL7D5rmt15.png',
    u'Конный мир': logobase + 'd8gVne1Em14rIfM6pSsiuufXZeYQqi.png',
    u'Конный мир HD': logobase + 'q87VlmfaBeBhq8SOhAu0SVPEGjiqWM.png',
    u'Кот ТВ': logobase + 'Rtdtc632nbBQ2TsymgXhkOt7nhytjW.png',
    u'Красная линия': logobase + 'I43S6jd5noclar0LlPJnyY8adonmUV.png',
    u'Краснодар ТВ': logobase + 'CCrPdzaCBrfMFx9vtrNWnEHoKlOkUl.png',
    u'Крик-ТВ': logobase + 'bYwacGhYkGwDoMsjGpDbltdCwMJSHJ.png',
    u'Кроха  ТВ': logobase + 'erfDIyaeH4D3DsiACWEEnutTEOvtpa.png',
    u'Крым 1': logobase + 'DXIF2fKXbbFRcKqPX1tgDA6iP6EWgP.png',
    u'Крым 24': logobase + 'x4s9QQXR8KerO13nlkuEujzcv5ww5F.png',
    u'КТК': logobase + 'BhI4KURCZ3fAgCQcwQWn7vRCJQblH3.png',
    u'Кто есть кто': logobase + 'MwNkO3fXd6KefRdiGlOdOQ5q0Zu7kS.png',
    u'Кубань 24 Орбита': logobase + 'FauvJxsKmI5a1fR62uSH9hJfHs5TCr.png',
    u'Курай ТВ': logobase + 'A0onEnFhSzqGxckeyyXsf0ZQ4R3Vc6.png',
    u'Кухня ТВ': logobase + 'G0WbVMphlP9oJ6KvHRfx0xDfhrF9Re.png',
    u'КХЛ HD': logobase + 'kRN7BwVtcdaXrU4Mdg24qhFAxjx9oZ.png',
    u'КХЛ ТВ': logobase + '216.png',
    u'ЛДПР ТВ': logobase + '1keO0CoTmw0B3VZRe4TZnzfGdKDqSj.png',
    u'ЛДПР ТВ HD': logobase + 'MDNGXlh8PC3Lo8Nlxzc2b80r2IGYsI.png',
    u'ЛитКлуб Проза': logobase + '6ToEP45fkncRbfekCJTCc2cJoVRMen.png',
    u'ЛитКлуб Слово': logobase + '5ohW4pvZ853qPJTZyub4jlrGR5nEEI.png',
    u'ЛитКлуб Стихи': logobase + 'YCTBulmYuDWfbkxv0ZaUlaR8L8SJiX.png',
    u'Любимое ТВ': logobase + 'qVREQyj0rN87jDZ1ylYW0sDvzfNp8p.png',
    u'Любимый HD (Кыргызстан)': logobase + 'O9BXnBIfJOjqyZLOfUR57k55fB56Ya.png',
    u'Ля-минор': logobase + '8FJA3xMMHcrZuGifHViyVQLjVIem5u.png',
    u'М1': logobase + 'ezvu2ugYMGnZ968LlnjPw7VjqWIPeM.png',
    u'М2': logobase + 'U4s78hznNz7mFYZQICkxN7J0HTtlCP.png',
    u'Майдан': logobase + 'eWxXMMlfQVUfZEIxGKsTqX15VRZUnN.png',
    u'Макс 24 (Сочи)': logobase + 'EkfRx44dYCkUuU7g0bM5jJz3bAASBG.png',
    u'Малыш': logobase + 'wTBr6XgnSIBFcGPyGXP4RwGmMzKcqB.png',
    u'Малятко ТВ': logobase + 'kjYF9vS2IDTMehpzC7WWfjnZ4NVpuk.png',
    u'Мама': logobase + 'nw9fROQIjjKSDp8Wjkjl1Wt0n0xHxd.png',
    u'Матур ТВ HD': logobase + 'eYwsH7VHWWsEWcWDiWxIEeGR8oZimR.png',
    u'Матч ТВ': logobase + 'hQDOuQjUVczvUU2ocLE0tkC1siCqpo.png',
    u'Матч ТВ HD': logobase + 'MXyy9Uud7oDuH8JqVisjsD0csgAHnQ.png',
    u'Матч! Арена': logobase + 'DDjh1dM2D09Wcl3L6YmEd1si3P17n0.png',
    u'Матч! Арена HD': logobase + 'DDjh1dM2D09Wcl3L6YmEd1si3P17n0.png',
    u'Матч! Боец': logobase + 'xj1tPp6g9LmQH5KAN0gFpWYoa9RdbL.png',
    u'Матч! Игра': logobase + 'urIB7TbFWo36EmXW9eG3w4qre7MdX9.png',
    u'Матч! Игра HD': logobase + 'urIB7TbFWo36EmXW9eG3w4qre7MdX9.png',
    u'Матч! Наш Спорт': logobase + 'l0x8GopxrHL6jLiDGVHi8tIEc7RBt2.png',
    u'Матч! Планета': logobase + 'mWQ92sSmszzmjme9GTueLPCxagJGtl.png',
    u'Матч! Футбол 1': logobase + '9PM8M6cN21wQ3M5isVZgjNepzUI4Ry.png',
    u'Матч! Футбол 1 HD': logobase + '9PM8M6cN21wQ3M5isVZgjNepzUI4Ry.png',
    u'Матч! Футбол 1 HD Резерв 1': logobase + 'HWZYoNrs7kQimfhyzT8V2d0WvBRbEr.png',
    u'Матч! Футбол 1 HD Резерв 2': logobase + 'jJsAF2rxef4RpccQrmfPkIbJc9kS7Q.png',
    u'Матч! Футбол 1 HD Резерв 3': logobase + 'Tpv0BbEi315Omo6MKh3ZiX5zTzc8OT.png',
    u'Матч! Футбол 1 Резерв 1': logobase + 'CWit8nYXCcCsmB6KbIedlKwFWWTyZT.png',
    u'Матч! Футбол 1 Резерв 2': logobase + 'n6kF2auPAk8bMH2zray20zP12QKL1Z.png',
    u'Матч! Футбол 1 Резерв 3': logobase + 'ipK5bpcm9mR9COdolCiHV6csIndprl.png',
    u'Матч! Футбол 2': logobase + '8MA3WloO6RsWX8N7Ck5ugek2Kirf4B.png',
    u'Матч! Футбол 2 HD': logobase + '8MA3WloO6RsWX8N7Ck5ugek2Kirf4B.png',
    u'Матч! Футбол 3': logobase + 'OLHdmyfUev4mMX0OGniJrlUwHnMKOg.png',
    u'Матч! Футбол 3 HD': logobase + 'OLHdmyfUev4mMX0OGniJrlUwHnMKOg.png',
    u'Мега': logobase + 'IXY7dRFoq0qCqn4UbY47iP36vVZ6ck.png',
    u'Между.Net HD (Междуреченск)': logobase + 'KIpCLdDqpcMhJuRLwKQC5fyUr1QHnM.png',
    u'Миллет': logobase + 'zDsxAdZp80tZ43Rd2IWAgFOFFYDkwh.png',
    u'Министерство идей': logobase + 'k9RMWD6a1nooGeVYJd5ULWhAx7nsTP.png',
    u'Мир': logobase + 'Oq6h2IicTagHENQu1mFkjLk5rChMnr.png',
    u'Мир (+3)': logobase + 'QxOYkz6f80IdhmC4RSHI1cMd32CqYZ.png',
    u'Мир (Беларусь)': logobase + 'tWFxseErqkMwEPfpQL7wG3g0YCtQHT.png',
    u'Мир 24': logobase + 'auv6717gJOWi0A2VoeDQaCsx9G1NOj.png',
    u'Мир 24 HD': logobase + 'BV3vqUP7OJt1MPjJW1sEjatzFb4jsq.png',
    u'Мир HD': logobase + 'Oq6h2IicTagHENQu1mFkjLk5rChMnr.png',
    u'Мир Белогорья': logobase + 'hoQtQmRjvTnuPxdAEAwc6xa4IJb9Ps.png',
    u'Мир сериала': logobase + 'XWDsU7aoUyPPoKfcX7WMYQheuzHJL0.png',
    u'Мир увлечений': logobase + 'KtELENmDesBwzAAryLgJPqwlr9m17z.png',
    u'Мой город': logobase + 'Ic42ai9oldwOstp4Y18ZKMrTGpVH2j.png',
    u'Морской': logobase + 'uzlb3awoyNqvIcf6i35hTVqf7gvuqz.png',
    u'Москва 24': logobase + 'dZcmoqRoZLhCBh8BE4RnbQivuDY6hH.png',
    u'Москва Доверие': logobase + '9oPazhJQrGZcSN64ZOS3WjLwGmQIZy.png',
    u'Московский образовательный': logobase + 'GH10kNmNEvHiF2VVqOdhCmAfY2s01m.png',
    u'Моя планета': logobase + 'Qa41eifERrD77xQsmpRGbeTq95Ldlv.png',
    u'Моя Удмуртия': logobase + 'l3xs5mws4kXBWbsjeVzS7tp9zttrpp.png',
    u'МТВ (Волгоград)': logobase + '7fHJRh8JGRjQzpxKQNaB9qYMBlcHqt.png',
    u'МТРК (KZ)': logobase + '13whXJN2Gjti9MbVSYTRaFVQFU6oKh.png',
    u'Мужское кино': logobase + 'y997iu65e65h4w5d3s4dy.png',
    u'Мужское кино HD': logobase + 'chlGvzPAZT5LtnV682N6VyD2JZ5umq.png',
    u'Мужской': logobase + '6YbhuWNqPKQWWsUGbBnSbAbm7IGssX.png',
    u'Муз ТВ': logobase + 'gttVvZmkAklbl2i0Mqy1MCzSCn7WiY.png',
    u'Муз ТВ Азербайджан': logobase + 'I2ib3azQXBr6JZMIVoXWOA6rhSX896.png',
    u'МузСоюз': logobase + 'E4a3fEpdSy2c8AnYEdR8ZIFgFe2LAP.png',
    u'Музыка Первого': logobase + 'fD2Hnsq5BPMGvobLDMPZP049yNhBYt.png',
    u'Мульт': logobase + 'ZVzHvGF8mZ6RTsSh6aWsPbF1FBLjyp.png',
    u'Мультик HD': logobase + 'SQMsd9Rj7Jsse16CyMqu0l7sW26WRf.png',
    u'Мультимания': logobase + '132.png',
    u'Мультимузыка': logobase + 'JyL1N1Hquqln9yz7bk8ARxpXdPklKO.png',
    u'Надiя': logobase + 'fvCkzRJPsTx4HONWPv3vPMjQNloPBT.png',
    u'Назад в 90-е': logobase + '7ooVSmIO3e0bdg1oPvyIcR5xtGIcJZ.png',
    u'Нано ТВ': logobase + 'QuURIfJUmXegxsHMYqMivVwxizbfKd.png',
    u'Настоящее время HD': logobase + 'Wh8dHDWVAik29wT1fdzdB9QClZ2PWv.png',
    u'Наука': logobase + 'OddcmNqjIGsNDv3hm5RkZNrrPwd8cX.png',
    u'Наука 2.0': logobase + 'ypWbqYqKApM8cnDK1FibvQgpmgEay9.png',
    u'Наш Детектив': logobase + 'Dj0hDhHdckvGp86dDi058HRBe6JLq0.png',
    u'Наш детектив HD': logobase + 'Dyn1YwipLFaVhYsrdCePlj9Zg6kCh0.png',
    u'Наш кинороман HD': logobase + 'NyV9o2C4xIMFxxYUQsS1qsdAtkqz0k.png',
    u'Наша Сибирь HD': logobase + 'HIQLr4dVs3zc3l8sUycMTiIeq86RoY.png',
    u'Наше Любимое HD': logobase + 'Z5nQ7tzooDcMRTSFmfJAerS8HAzf3q.png',
    u'Наше любимое кино': logobase + 'LSR5M6VxB0YDwv6803zrGFkq7vGQ3J.png',
    u'Наше новое кино': logobase + 'y5jtghJCHG65ukyfjv 45stjxc76.png',
    u'Наше ТВ': logobase + 'gTfxpSWtOGWBq7UHAHcz3XF10bzg78.png',
    u'НВК-Саха': logobase + 'pzAnkRgC2Hiq61oZUAC08ym6cYCNbv.png',
    u'Неизвестная планета': logobase + 'Gvam2aif9yVwK5YjswZ43GQOwc9ZBJ.png',
    u'Ника ТВ (Калуга)': logobase + 'HioADhpbooxJoYDpG4yZHsTEYAkWDu.png',
    u'ННТВ HD': logobase + '0lWQ6PSAFGo652xEsi2ISmr3yIySFN.png',
    u'Новое Радио ТВ': logobase + 'hyChk0D0HyMcgJhXH7uBm9QrzhxP6F.png',
    u'Новое Телевидение': logobase + 'ZIHKHMvdpUDHf1rwaCeKLrjSi497Zu.png',
    u'Новороссия ТВ': logobase + 'myb7uAMDOPvF0SdQa8SsZHy6Yl2iw0.png',
    u'Новосибирские Новости': logobase + 'x1FJLH1GsOqhRDBLJcFScrjgwTFkQd.png',
    u'Новый канал': logobase + 'k7YdHhVpFZPIkBMXS2P2O2TkZSPf0y.png',
    u'Новый мир': logobase + 'K0Oy2d445QmB0921HH1aB5JWUGScto.png',
    u'Новый Христианский': logobase + 'gf6hTOcGXasvr47vTFRYZGV11xkDr5.png',
    u'Ностальгия': logobase + 'tIfiXoDaXoZevuGu9pZJSvX8unv1xl.png',
    u'НСТ': logobase + 'fKYzdlWRz68qd9mRZnWuxMY73EyaSz.png',
    u'НТВ': logobase + 'B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png',
    u'НТВ  Молдова': logobase + 'WsntXIkTDI5jlYhDhFNJkt9NlpCzja.png',
    u'НТВ (+2)': logobase + 'B5GA1cfgmn8EsxrdwfNUIrEbdqarXf.png',
    u'НТВ (+4)': logobase + 'dJ5M9w82M5EAPdz7sgDePvBkUae4GM.png',
    u'НТВ (+7)': logobase + 'R3lh5bVsq1ocEE5eGsohaMtkAxDhaF.png',
    u'НТВ (Беларусь)': logobase + 'kF0n5BZzggqrBd2rPSyQKuGtC5YuCR.png',
    u'НТВ HD': logobase + 'zdJ3ye6d3UWl5a56zm6LjqYH6ziSOs.png',
    u'НТВ Мир': logobase + 'lppYCLErwswZLVXM0zwwLI7gWMEslg.png',
    u'НТВ Мир Балтия': logobase + 'ykpU49Gl1akVkgiVSsCm5B4TjXvQ64.png',
    u'НТВ Право': logobase + '7yNDqWT8KiQ2aa9kGYXSsnVFCPj5xx.png',
    u'НТВ Сериал': logobase + 'T7amR78JUYW3EgFZp14hQdh7pjzWLJ.png',
    u'НТВ Стиль': logobase + 'DjeH6JTGT2hH0Y1Vfwd9Cceg780nNl.png',
    u'НТВ Хит': logobase + 'vTsJWJKjxzUvoVni2GAiTfXlWwDtuY.png',
    u'НТВ+ Инфоканал': logobase + 'civklbbvKleqSPs1A92CB6cEtuxo3K.png',
    u'НТК': logobase + 'ix3lD9BcsoKou0MIhUCGgKF9MypV1g.png',
    u'НТМ Телевидение Мордовии': logobase + 'q2OxQOCLRBtW7zKsZqIgQzU9697TEW.png',
    u'НТН (Украина)': logobase + 'LpQE1Odb1EoH5dJ90gWjItVyEYBXsw.png',
    u'НТС (Севастополь)': logobase + 'TXAYiNGbuk9rq4SJFkVhOLrf5xsziE.png',
    u'О!': logobase + 'zHhfMQhsdu59e6puujg0qHt1675jYO.png',
    u'О2ТВ': logobase + '7KCLIwxu4Rfly2aMpR8zWBGvpv1Py8.png',
    u'О2ТВ HD': logobase + 'CYmynLDPSgp83cQp5NCAJKstj8RiR8.png',
    u'ОНТ (Беларусь)': logobase + 'a84If8XdqSFa6nHpegdujt52vAGNJW.png',
    u'Оплот ТВ': logobase + 'iOSHk1wp80LBLW9jNMTktRKYIOMK0N.png',
    u'ОРТ Планета': logobase + 'K6In8ZCBevCfeezQhSmatrK88JFrHD.png',
    u'Оружие': logobase + 'CyDUCmYXK8WS2kXCX5kiAOFejnlwoP.png',
    u'Остросюжетное HD': logobase + 'mxF7CZsqsDRMMK4pN8ekdccEgvEsZC.png',
    u'ОТВ (Екатеринбург)': logobase + 'CG2wNeit7eOZOkJGRAwMb1abm28XqB.png',
    u'ОТВ (Челябинск)': logobase + '4mHWgXLiBXAzd9MbEvoSUp7LDyCoUz.png',
    u'ОТВ HD (Челябинск)': logobase + 'PJ6O6K8WcAZihwqeWkAyHnBY0aazCq.png',
    u'Открытый HD': logobase + 'CdIvMNsa7gAihJnpAKX8QnMdpvhAXc.png',
    u'Открытый мир': logobase + 'vzFPGE5EMEh8ilV1WIGYcCKwYVVTSZ.png',
    u'ОТР': logobase + 'CqxKorK72v3ULbWkB3ZOhdte0duYZa.png',
    u'ОТРК Кыргызстан': logobase + 'hIWpQ871mPcb60jh6Fxe3X21i8AWKm.png',
    u'ОТС': logobase + 'OorjYCuo91DUKG24nicUWcVTLdElzR.png',
    u'Охота и рыбалка': logobase + '5l2P20J6ebTh0ptOr27Hh704niP3nU.png',
    u'Охотник и рыболов': logobase + 'Ws2ddPI0b5Ie7PymoPUsboVlz9lYMS.png',
    u'Охотник и рыболов HD': logobase + 'O0wexOqiQXKMwr2coDMKWvJEb4zLQ1.png',
    u'Парк Патриот HD': logobase + 'rTZqyvIejwQV3IDWh4q0wgIXFm2Gpr.png',
    u'Первый автомобильный (укр)': logobase + 'oZTXrmNOxeJIVSbnuxqbiuAL3voXYa.png',
    u'Первый Балтийский Канал': logobase + 'Eb0Gmf3svwZOwq3JuBcNGPEbVQeffn.png',
    u'Первый вегетарианский': logobase + '5fWQMPg68zESR9EY5sfUqB8rWJTsSS.png',
    u'Первый Городской (Казань)': logobase + 'hzkH7YIMy5jvaEWnPTXTzKKvNwZtOe.png',
    u'Первый Городской (Калининград)': logobase + 'f1qnl3wwkJKbfUpsaue3yMfG2CNaJH.png',
    u'Первый Городской (Киров)': logobase + 'DoKQvt9mUUYEwhXbO4M6PgGOAhok1X.png',
    u'Первый Городской (Кривой Рог)': logobase + '8cJVGXI2tnmH0KZHXmzNtSp6yYTBat.png',
    u'Первый Городской (Нижний Новгород)': logobase + 'KIk38UE5KUocmPblv2gkPZZOV77Feq.png',
    u'Первый деловой': logobase + 'a1Qf3MpxC9FPD68Tj8vtUTNK8P25xr.png',
    u'Первый канал': logobase + 'WimZD6efLd6QotrPP9uiJeF7t50nFv.png',
    u'Первый канал (+2)': logobase + 'GGe1ttMtczS0mgzMCegYji57J3PIaJ.png',
    u'Первый канал (+4)': logobase + 'nUznF8VjPtO3KwbjlU0KaSWhutRRaL.png',
    u'Первый канал (4:3)': logobase + 'WimZD6efLd6QotrPP9uiJeF7t50nFv.png',
    u'Первый канал (СНГ)': logobase + 'sgHReQnscPMIJgfDJf0uRFzxVBRKx9.png',
    u'Первый канал HD': logobase + 'VxAFWzh1y88c8Aqa17TsxD2IO5pqoi.png',
    u'Первый канал HD (+4)': logobase + 'VxAFWzh1y88c8Aqa17TsxD2IO5pqoi.png',
    u'Первый канал евразия': logobase + 'UxAkAKQZ2gNllniwvJzbGfpqQLGDVU.png',
    u'Первый канал Санкт-Петербург': logobase + 'yA2AL1ogAUppNx0dyPvMZzpvvJwuC7.png',
    u'Первый Метео': logobase + 'vdA7FKd1SCYhX4ovvzjQEHFdW3uA5X.png',
    u'Первый музыкальный HD': logobase + 'YxKl6Jqi6fmlUJjYGPnBhWhntKzI65.png',
    u'Первый музыкальный канал': logobase + 'gYpYhzD3akuKSFpRmkh2p36pXnqHoW.png',
    u'Первый музыкальный Россия': logobase + 'MkX2WG1zhZ2KcYFdL0xWH1T4xkO7UW.png',
    u'Первый музыкальный Россия HD': logobase + 'h7EDhdGypKmtfEP98O052SLlXUCcXt.png',
    u'Первый образовательный': logobase + '1kXxtStMuodaPU09H3rla3ry3QA2Wr.png',
    u'Перец International': logobase + '9cyKPQhQOU8rit0AtsUtc94nIhd54J.png',
    u'Пёс и Ко': logobase + 'PRKXfrhZdXbyczPrkbbTeV6Or4TXBR.png',
    u'Пиксель ТВ': logobase + 'BdCXB7wPZMNvlWzB5xEFzmsYUXcfXW.png',
    u'Пингвин ЛоЛо': logobase + 'YDdoeSLiTavidDXKYt44BG3ALdq5pq.png',
    u'Планета HD': logobase + '1QjirpCLi3q9qPu1CTvEvCB0BfINeo.png',
    u'ПлюсПлюс': logobase + '6gVIy7RMokFO61iVawgwbthe5mhgqm.png',
    u'Поехали!': logobase + 'fFbZjxWmyR56mJrPNSgm34uzsG74M9.png',
    u'Правда тут': logobase + 'ioOMiI0myM3KByc74cuRbONjyKvK2i.png',
    u'Правда тут HD': logobase + '9QLJwYZTf6r5asBpRvlw92xTWxJnLj.png',
    u'Приключения HD': logobase + 'pGM4tozKksBqooWcNRNKr0xG2c5WUN.png',
    u'Про Бизнес': logobase + 'mDyMXzimIOs0wZ2ihgPzdO1SvrL7b3.png',
    u'Про все': logobase + 'S2i01pmEOFJxwJtJCVF7PYc6Ij4jBX.png',
    u'Продвижение (+4)': logobase + 'B1xkAdSB96uFgb5R90vejFjsUKXrbc.png',
    u'Продвижение HD (Омск)': logobase + 'qmaGd81WFsVDntpeM8KcNU1mATTV4N.png',
    u'Просвещение': logobase + 'Fpx3Vqqk2VNcXl4YjsfO53XscWadvF.png',
    u'Прямий': logobase + 'GQ18MgdhsT2vfFTX9jk4buMPP0BXtx.png',
    u'Прямий HD': logobase + 'iU5W4KhtdJAJflaxRxuKlk2158HkUj.png',
    u'Психология 21': logobase + 'AyLAdiqcKu5X8ykdLf2bO9HsxMlJdO.png',
    u'Пятница': logobase + '0fafj6PSIWdqtBdgwYTl9M06SDU2wA.png',
    u'Пятница (+2)': logobase + '0fafj6PSIWdqtBdgwYTl9M06SDU2wA.png',
    u'Пятница (+4)': logobase + 'Egk7R3ZYUxFObktv2Ry1BqFQRE7ioe.png',
    u'Пятница HD': logobase + 'CbqoDsl3lLtkXN5kmGmWGO87SpUHpo.png',
    u'Пятый канал': logobase + 'nIUDYY41OO4Xo0ntGpGv2rfpOR5ngt.png',
    u'Пятый канал (+2)': logobase + 'rsEtkBk2ta1Wj1Y8uvxvSm4Vmbycir.png',
    u'Рада (Украина)': logobase + 'hBFJBYNiqZUom0ooVtNEJKliZwfioO.png',
    u'Радио Шансон ТВ': logobase + 'UeSZRz7c0zcwdvilqAcEgY58jS8NGb.png',
    u'Радость моя': logobase + 'VRylZFYgFq7AL0FWcbf5JVOX3desn3.png',
    u'Раз ТВ': logobase + 'CWaPSXdAL4Ejo1wNOqSWNPNVwbbhC7.png',
    u'Ратник ТВ': logobase + 'vSP71XjEvnRcGUzqdBCTptovj78BzF.png',
    u'РБК': logobase + 'JUMDXZxxB3UiVpMpU8t0aCpbVzxTmP.png',
    u'РГВК Дагестан': logobase + 'qn17bOV3KKdSlA4iY9wM3QQGjSYv9f.png',
    u'Регион 67': logobase + 'raRsHqtFzXbjAlKGviKbT3abWswEQf.png',
    u'РЕН ТB HD': logobase + 'RP50DZTOq2eKRyfC6BmJi4LEYbIElu.png',
    u'РЕН ТВ': logobase + 'LJvkfB2kYaDzij1Y13Fy6syUCkP5Y6.png',
    u'РЕН ТВ (+2)': logobase + 'LJvkfB2kYaDzij1Y13Fy6syUCkP5Y6.png',
    u'РЕН ТВ International': logobase + 'do84cS9lBxE3okiGXsxVbZWHwL3NAP.png',
    u'РЕН ТВ Балтийский': logobase + 'Nmrj8WVKFILAIs0sqcf88hEcAv3xsc.png',
    u'РЕН ТВ Санкт-Петербург': logobase + '7nsKeNaKq9KdHgFjeZu4DVmJOv9rCV.png',
    u'РЕН-ТВ ИСТОКИ - ОРЕЛ': logobase + 'zQdW4sGEnQaBi2EJMNqz9A9069Jm2q.png',
    u'Ретро ТВ': logobase + '5vuRj5ip04YKBNM60rdB7aFueKvypo.png',
    u'РЖД ТВ HD': logobase + 'cqp5hEglDGFImvFyt1tVUJsz91XxEQ.png',
    u'Родное кино': logobase + 'y7saqicb538iqo64ho46hh46.png',
    u'Россия 1': logobase + 'UUrfoqi6NQcc9gRLnCc8ODZJ2T3ShE.png',
    u'Россия 1 (+2)': logobase + 'TmknFdEdaX9GxcJhqd856oKgv0o1lp.png',
    u'Россия 1 (+4)': logobase + 'buzygzarNA0VXEEKSE2oMALmjSxwao.png',
    u'Россия 1 (Новосибирск)': logobase + 'aj3UxSavWLzV8L6Xj3FSIHLXiyL5Q7.png',
    u'Россия 1 (Чита)': logobase + '508Yuw2bkpv4J4x9LYXOPayVeBbbrq.png',
    u'Россия 1 Красноярск': logobase + '7F8EgXQfDI4Fwl0jbdd4cV7ELU9lH4.png',
    u'Россия 1 Нижний Новгород': logobase + 'yJmjafi9Ac5lKXPe0nlQi122Dpu9nN.png',
    u'Россия 1 Санкт-Петербург': logobase + 'QTHFZkkuVC49pKOtXvKSuYtbP7DsGe.png',
    u'Россия 1 Севастополь': logobase + 'Z6zY2ili4kDj0V228yz6gj4C00x6az.png',
    u'Россия 1 Сочи': logobase + '6z3BhTq9pVgb7bsf8xMWQPzqBy8mdF.png',
    u'Россия 24': logobase + 'LWfGV6eICPYL7psaBfw2dOgGrOtHFS.png',
    u'Россия 24 Красноярск': logobase + 'hb4Gx8ffrkQT7P7gloyRBY7tKsAQ2e.png',
    u'Россия 24 Нижний Новгород': logobase + 'bo2pK1XmsW9Xh47hUzNZCmB179qO6k.png',
    u'Россия 24 Новосибирск': logobase + '2c3EBYf2d4CRaNfw8hcufICSf75kqI.png',
    u'Россия HD': logobase + 'ghvqmVpPWqn9x6POAm9UJBvXFzTrqN.png',
    u'Россия К': logobase + 'W9pWrec1BOJTmj8okrFeyM44wcpyd4.png',
    u'Россия К (+4)': logobase + 'UQlUT6RhNj7rncSJhFYx0nmzRaDGRN.png',
    u'Ростов Папа': logobase + 'b460sFMOsMyHYywC8FYGY4zl2SrmSx.png',
    u'РТР (Беларусь)': logobase + 'pEdoit46pnCnyA9Ovt0GM0kT1coGe4.png',
    u'РТР Планета': logobase + 'jgQeBwyqQI1Qh1r2aeOK5NiyPtcjTd.png',
    u'Рубль ТВ': logobase + 'JFScsKfJKgPtHLiLIpqAmoIOKVEUPP.png',
    u'Русская ночь': logobase + '9Sh9bJuj6js5AJsypAd6UvwnsIB25R.png',
    u'Русский бестселлер': logobase + 'b5JXaosgmcanh9EVJg52yBefvdLQF7.png',
    u'Русский детектив': logobase + '7I7VjbsFMIkZdoSbHFXiKEVZKNUbOM.png',
    u'Русский иллюзион': logobase + 'E9Imfr8aHN5midPVpNhJ3fo49FHbQE.png',
    u'Русский роман': logobase + '2smriIFxtj7Ojh4jyZq0K1XrT98XjS.png',
    u'Русский роман HD': logobase + '2smriIFxtj7Ojh4jyZq0K1XrT98XjS.png',
    u'Русский север': logobase + 'pbTh68DsXofFQoIt0cf8GvjeSWtd7l.png',
    u'Русский экстрим': logobase + 'upndVpIdjY3vb5vrituof5UcKISNcQ.png',
    u'Русский экстрим HD': logobase + 'upndVpIdjY3vb5vrituof5UcKISNcQ.png',
    u'Рустави 2': logobase + 'Jvy0ftVe3EdjJwzJP0apAobN1anWd7.png',
    u'Рыжий': logobase + 'wfBSy60qHaPSKPpTfrNv9Q167iHIPu.png',
    u'Рыжий HD': logobase + 'eW7CqWW2bppbpKzhNctyElyv5Nzs30.png',
    u'Санкт-Петербург': logobase + 'sb81YtPOvlHidztMnC5tZPSKkb1uMI.png',
    u'Сарафан ТВ': logobase + 'LsYzwEOUspoxkY2hrTSy9zKqvpWlY8.png',
    u'Светлое ТВ': logobase + 'TI5r40h6Un0bHj8MIVkx6qMJRJTHqa.png',
    u'Север': logobase + 'EAdWnfCRNc1R8oVZeO7vO355V87AzM.png',
    u'Синергия ТВ': logobase + 'PSh5vmPdvqhD1yIfBGyGsx0KJfu876.png',
    u'Сказки Зайки': logobase + 'ate5hd5vMAzbydl6dVpG6CMyxnqKnE.png',
    u'Скат 24': logobase + 'akvOzQdWpUosm4OXHwqidYPvzCAGqc.png',
    u'Смайлик ТВ HD': logobase + 'l4eM2nWbsJxQNKgUP7D4XZ96ieTkb6.png',
    u'Совершенно секретно': logobase + 'BZJQEpa6Y4KL9tQjPHAIxbodw0KAyN.png',
    u'Сонце': logobase + 'TJXJVeoBFRMFrUgzpPW4dunJL6XSzn.png',
    u'Союз': logobase + 'YpsuBorUwulPHW3nI8O6nKETnEVB83.png',
    u'Спас ТВ': logobase + 'pAFeyS1iCV4BybnpnnwjoKm0y0zvaA.png',
    u'Спорт 1 (Украина)': logobase + 'ylqYg65rhE7boiz0QkrOyAYG9wsBjS.png',
    u'СССР  Фильмы': logobase + 'ISR80qA7xHpcze5kOGWCgRf0MaoJSK.png',
    u'Старт ТВ HD': logobase + 'K9YS66Hf9QHrP2HIgzYLxNdgMfmahf.png',
    u'СТБ': logobase + 'saZlIDrdaXWoiQa8sfZp2bEAeH0kXk.png',
    u'СТВ': logobase + 'XX9KxgBXMkvJkP1PeUshGI1pe43Huc.png',
    u'Страна FM ТВ': logobase + 'ysrRW9deFkccNGlhtT0Sww5Yt8IpY1.png',
    u'СТРАХ HD': logobase + 'QIFxORu92dl37nKMiVAMghjxAewcV8.png',
    u'СТРАШНОЕ HD': logobase + 'rxkVCQjzTHZc8r20vv22w9lZP9uVpW.png',
    u'СТРК HD Сочи': logobase + '2PphESGueDUS1T6wSOr12iTgTbIVJm.png',
    u'СТС': logobase + 'is620Pu6DreVLLnpHkpcXXZC9PI2Hi.png',
    u'СТС (+2)': logobase + 'OQ2oVt4sEUWx6RpHUavTvol4QUS8El.png',
    u'СТС (+4)': logobase + '9kPWMgG96ZZcBeleMogGOHKZcsOARf.png',
    u'СТС (резерв)': logobase + 'is620Pu6DreVLLnpHkpcXXZC9PI2Hi.png',
    u'СТС International': logobase + 'is620Pu6DreVLLnpHkpcXXZC9PI2Hi.png',
    u'СТС Love': logobase + 'iciJHbEmJ1hHXAMhzC9cRWhmh9gH0L.png',
    u'СТС Балтия': logobase + 'czsY6K8Xk71UE2M0zSqsEYvsP98vFX.png',
    u'СТС Красноярск': logobase + '7yGK9Owq7745vx0Pta8WuXMP2FMuX0.png',
    u'СТС Мир': logobase + 'ULrMy9Ra8rDsfTz471UNpS3mLxiNMm.png',
    u'СТС Прима': logobase + 'XFMk1NOZ9bzFFRdGQsJnw9DfAd8RNS.png',
    u'Супер': logobase + 'lGHuG6fgZVQwxtBNJxK1sefakkvKOe.png',
    u'Тагил ТВ': logobase + 'lVAAcq7ZOY9PG3RczefUKVU57R6agJ.png',
    u'ТБН': logobase + 'r9O7HmwQbFR4oKMH9yKAogE8xBzwz4.png',
    u'ТВ 3': logobase + '07bjT0brQLyETHscCfGFtvsdaRiUdH.png',
    u'ТВ 3 (+2)': logobase + 'cO28FY3ZV4SmelCz6LF8J1ZjtK6cNs.png',
    u'ТВ 3 (+3)': logobase + 'L9mntoII4s1UyzlZxoduwBsBBvZDps.png',
    u'ТВ 3 (Беларусь)': logobase + 'v8z7nvwpMoyULnkDBKOPuwwAkLsTke.png',
    u'ТВ 3 HD': logobase + 'Kto89eK6OdrV2G5WKhh42tqt9HWWdv.png',
    u'ТВ FM': logobase + 'A3YxOjZfAw2KJ3naZrCznXfdlotAlw.png',
    u'ТВ Академия': logobase + 'v6Fu5wilul4Y6iw0bhuqBV8jHIKXHO.png',
    u'ТВ Тур ТВ': logobase + 'ob8dZG97W5eCoM73jwgt6CLHVlteHp.png',
    u'ТВ Центр (+2)': logobase + 'usxZjPcMsaBT4bH9A6wyZltOdd4Tti.png',
    u'ТВ-41 (Щёлково)': logobase + 'rZ5191mHhhi63SD4I5QnhL1RcrnB1l.png',
    u'ТВ21+': logobase + '23SqI2GpkIpWzectgprX7yoByzuYrr.png',
    u'ТВ7+ (Херсон)': logobase + 'gQk9GyiR7fRwFVT5uGBVEspJX8wJqn.png',
    u'ТВА Черновцы': logobase + 'YqrIn8xvKey5FM5f68HitkXe2Rc5Gn.png',
    u'Тверской Проспект - Регион': logobase + 'ruGWnnymbc0qOKGx8wExM85LER3s22.png',
    u'ТВК 24 (Красноярск)': logobase + 'GSk0pFHioAZscQ2ZJeM8QR9TybJlRk.png',
    u'ТВК Бердск': logobase + 'a0dxq3ShthsKAnf4rszHtRxOXL5DO8.png',
    u'ТВК-Домашний (Красноярск)': logobase + 'R6ZuU6wW1NKgjx8WsjlltgisdiI5iF.png',
    u'Твой Дом': logobase + 'TJCGg7LuuUfVsyv5IFjMPLAGZmlNNL.png',
    u'ТВЦ': logobase + 'QEpQTskZ9hcfI0rgD8osHVYSv58pde.png',
    u'ТДК': logobase + 'eSrHE6Gws4U6JxhFXA3mQ4iDVc0SwS.png',
    u'Театр': logobase + '8qawrcOtzHZTAa3kI0rcDfVFEZoI5u.png',
    u'Телевсесвит': logobase + 'luOXi9wlWDPOnpoh6HGvnHKn6VRRqY.png',
    u'Теледом HD': logobase + 'XviuCfRo0T4WFTOhFaC978AwZ1a3Ge.png',
    u'Телекафе': logobase + 'fYRFV5oY197jXcyModfWVs0AlrCOIs.png',
    u'Теленовелла': logobase + '3xwk37m9ymdTdDUVwdYkO9bY93tWfB.png',
    u'Телепутешествия': logobase + 'fz4bqwLySJAQkUN7l2EPKNqyvilfRD.png',
    u'Терра': logobase + 'GfIwWExYktvecczAx1jL64Rk8xdyea.png',
    u'ТЕТ': logobase + 'jp0YxRwXOyMWgVfDAyQaXNwle90sV3.png',
    u'Техно 24': logobase + 'JbUGHLuuZa3WQbjtbzUo0cDZkGnLRK.png',
    u'Тивиком (Улан-Удэ)': logobase + 'pmpDAszrs92s6r2qzSAyEtvcQ0Qkh6.png',
    u'Тиса-1': logobase + 'pPRRy0SjPl3JKXdcZrQrdXQz3NTKOH.png',
    u'ТК Центр Красноярск HD': logobase + '5u8ySiocN2nMFbtQYhmgnuceWc3FUB.png',
    u'ТКР (Рязань)': logobase + 'F8OjHF2yLtSU2zTf4gg8dbqdS8j1nK.png',
    u'Тлум HD': logobase + 'FhxsethirEr5lhrE54VGA4acHu7MJn.png',
    u'ТНВ-Планета': logobase + 'vBMv8AtIpDhBGQLjPoxkko3baWMFac.png',
    u'ТНВ-Татарстан': logobase + 'kMdYm3qFLgK52EV0ymvRBB43peSrj9.png',
    u'ТНТ': logobase + 'Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png',
    u'ТНТ (+2)': logobase + 'Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png',
    u'ТНТ (+4)': logobase + 'Vtt1KKIpLY4LTQGnV03sdBYyX3hyWR.png',
    u'ТНТ (+7)': logobase + 'lBHVGkAE8EVjDXLQGl52H6HTLavzBR.png',
    u'ТНТ (резерв)': logobase + 'yEDrU5cgZbdUgfq8kzb40581xLcXNy.png',
    u'ТНТ HD': logobase + 'iD2Gi2nqvSSZnrtPeaqAp6M3NpD50v.png',
    u'ТНТ International (Беларусь)': logobase + 'd4loXdWqOPiwF7thzyBXX8JSspfVjU.png',
    u'ТНТ-Music': logobase + '6Go23tY9hpakfrvTEUH7Z7o5Y9hpOG.png',
    u'ТНТ4': logobase + 'yTclqOAW0EWwhw9vt0spVSUcS70ZR0.png',
    u'ТНТ4 (+2)': logobase + 'yTclqOAW0EWwhw9vt0spVSUcS70ZR0.png',
    u'Томское время': logobase + '1Z7yLtfyuITQhXchO59gwyQ3mES7qS.png',
    u'Тонус ТВ': logobase + 'bE8WfReOerYTIbqPOo6VD2ajrFdOBT.png',
    u'Точка Отрыва': logobase + 'UbSjKv1Cv0iHZVcfBOEAc1RvTg7A13.png',
    u'Точка ТВ': logobase + 'JWwPbPnkWooIpKd5WYsdpfO3Mh14oA.png',
    u'Третий Цифровой': logobase + 'MXcua7OlJ9CplpD15hD84Xn2QjoCdt.png',
    u'Три Ангела': logobase + 'EphQD4X09CGs9ukmPVM5FpmQBSyvch.png',
    u'ТРК Заречный': logobase + 'cYr3OdNgVOZh29q0YjCffEIINY4zh3.png',
    u'ТРК ИТВ': logobase + 'R4yGs2QhwjUEiDS85nU7fgmy7WdD6o.png',
    u'ТРК Киев': logobase + 'qW0p5z3De7COmSxTmvJ4ZA2wOuSJjg.png',
    u'ТРК Луч (ЯНАО)': logobase + 'CVcjfhpnfMyV4uRoXxHsvvP9hD21QQ.png',
    u'ТРК Украина': logobase + '0co3dwhFDhoCVeTbfMV8ASYFYxSrWM.png',
    u'ТРО Союза': logobase + 'xAXy9iMyJ4wa2wmugJvbZuDIzc9pVz.png',
    u'Трофей': logobase + 'tQTWwjNBC8aLLWiWZfCj43BhWNH51I.png',
    u'ТТС': logobase + 'crsSIipA6N288sjn4EvUyOyTd0ed9A.png',
    u'Туран-ТВ': logobase + 'JgbnQUGSrXJRAoDBRtij8B1tyqi42E.png',
    u'Тюменское время': logobase + 'qkPgjRxC93PEe4UaULFXjL9INo4XkC.png',
    u'Унiан': logobase + 'fhpFrTDoI9xx7UlK65KAjAbdTGehLL.png',
    u'УрФО 24 HD': logobase + 'dO2b0PDb8ubcYjL4ZxLyZTQ7xjPn0q.png',
    u'Усадьба ТВ': logobase + '3PdlNOdFo973qiGewntvIRanZF6MgP.png',
    u'Учалы ТВ': logobase + 'ZzGtKMOaksyDZNYkBTU1VkNOJWhkvb.png',
    u'ФАНТАСТИКА HD': logobase + '4UHpHvRnNJfATQSoLNYWrA38TrNDkv.png',
    u'Фауна (Украина)': logobase + 'tuGtX9QIXM8h6O6RQoL3S0Gm7a23Zg.png',
    u'Феникс+ Кино': logobase + 'idiNkkBsxLwxWCF2VZrc9LQEevKh0d.png',
    u'Футбoл HD': logobase + '4TSPtZYIdL64QjL4GYcvSCyWBssx7B.png',
    u'Футбол': logobase + '472.png',
    u'Футбол 1 (Украина)': logobase + 'AMKtYwcgSAX5mTcPdhQDe4he18Jz7S.png',
    u'Футбол 2 (Украина)': logobase + 'PUXTI9mKcs49JnEENkh95KoKqt9VNg.png',
    u'Хабар 1': logobase + 'gSdsXibLuZlpsfGw39KofcsLiq0zm8.png',
    u'Хабар 24': logobase + '3b7IxeZ1570x0KPYBXW2nt3EwRY6Ss.png',
    u'Хамелеон ТВ (Киргизия)': logobase + 'j6feb5UuXQd4wOQaA3MvEm0loPW5na.png',
    u'Хорошее кино': logobase + '9kWkXFAAlhXRtSpF3VJgVD0eMsqRZQ.png',
    u'Центральный канал': logobase + 'vzfLS14qVT0rSphoNeEuO2WDvXFoub.png',
    u'ЧГТРК Грозный': logobase + 'LqDNdQj6nf4MraZztT6ZnACn7yOJpV.png',
    u'Че': logobase + 'Hv36ZG48lg1mm2wdxAo3ju1EFS41Ga.png',
    u'Че (+2)': logobase + 'HYWZATW7uW3ajRR7ULEZxcVteqHIqt.png',
    u'Че Красноярск': logobase + 'xPABlShxQMUQdMfwLvJXC0ugNoYutK.png',
    u'Черно Море (Болгария)': logobase + 'CoJWFBn5c6GaSBHP9D0wSPcCCXX2yP.png',
    u'Черновцы Телеканал': logobase + 'GOFMsDHSbl1cFmcCqzt7I6YVYffOme.png',
    u'Черноморская телекомпания': logobase + 'LJVoPVcJAE0s4DNmXCga0UPZkRkLTq.png',
    u'ЧП-Инфо': logobase + 'Xy7mLl3exaBKuLlDGdrRls6hyR7mSw.png',
    u'Шансон ТВ': logobase + 'VY0TyCCkKOj5b8BhBJjT020sQoxL9F.png',
    u'Шансон ТВ': logobase + 'W9oVFhL4LJTetfz0U7rR1Vgo1G09xC.png',
    u'Эгоист ТВ': logobase + 'moG8uExVh4nw3MN7dmGFdysJHBWLk6.png',
    u'Эко-ТВ': logobase + 'EmsE2NuqzHi5NXh6OIMMXQpfmD0VIl.png',
    u'Экспресс (Пенза)': logobase + 'Q64Gc1m4iaG51bDQ13s8I0uVlq0Ugj.png',
    u'Эфир 24 (Татарстан 24)': logobase + '8H6PLKiehQgY46uEPLIzebfSTSnwIx.png',
    u'Эхо ТВ': logobase + 'MwXfKGSDbPHr1K4mCWdq7LAM7ypTob.png',
    u'Эхо ТВ 24': logobase + 'p9PSR3UzBG3Y2HiNQNYLO9CpTQ5nkq.png',
    u'Ю': logobase + 'YvnG7hXCwMmHnakp2KkCbqeCigHcuK.png',
    u'Ювелирочка': logobase + 'pvKHFUCv25R51hJoUpAJfvjGnWyqoZ.png',
    u'Юмор ТВ': logobase + '6VFA1SVxeFHUsGaKPbNxWZREDkGeZw.png',
    u'Юнион': logobase + 'LxlKvATpTBI1eGDU37k7vDbUsww9kU.png',
    u'Юрган (Сыктывкар) HD': logobase + '1IlYx94MKrETrrrV9PEWkb8qZeLoFg.png',
    u'ЯТБ': logobase + 'cFbeVL4YTqBkib0TtJxet8XvTK9ZED.png'
}
